/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TechnicalAnalysis,
  technicalAnalysisSchema,
} from './technicalAnalysis.js';
import { Trend, trendSchema } from './trend.js';

export interface AggregateIndicators {
  technicalAnalysis?: TechnicalAnalysis;
  trend?: Trend;
  additionalProperties?: Record<string, unknown>;
}

export const aggregateIndicatorsSchema: Schema<AggregateIndicators> = lazy(() =>
  typedExpandoObject(
    {
      technicalAnalysis: [
        'technicalAnalysis',
        optional(technicalAnalysisSchema),
      ],
      trend: ['trend', optional(trendSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
