/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AiChatMessage {
  /** Role system/user */
  role?: string;
  /** Content */
  content?: string;
  additionalProperties?: Record<string, unknown>;
}

export const aiChatMessageSchema: Schema<AiChatMessage> = typedExpandoObject(
  {
    role: ['role', optional(string())],
    content: ['content', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
