/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AiChatResponse {
  /** Chat ID. */
  chatId?: string;
  /** Response text. */
  content?: string;
  /** Query summary */
  querySummary?: string;
  /** Related queries. */
  relatedQueries?: unknown[];
  /** List of tickers mentioned. */
  tickers?: unknown[];
  /** Sources. */
  sources?: unknown[];
  /** Widgets. */
  widgets?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export const aiChatResponseSchema: Schema<AiChatResponse> = typedExpandoObject(
  {
    chatId: ['chatId', optional(string())],
    content: ['content', optional(string())],
    querySummary: ['querySummary', optional(string())],
    relatedQueries: ['relatedQueries', optional(array(unknown()))],
    tickers: ['tickers', optional(array(unknown()))],
    sources: ['sources', optional(array(unknown()))],
    widgets: ['widgets', optional(array(unknown()))],
  },
  'additionalProperties',
  optional(unknown())
);
