/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AiChatMessage, aiChatMessageSchema } from './aiChatMessage.js';

export interface AiChatBody {
  /** Messages */
  messages: AiChatMessage[];
  /** Stream responses */
  stream?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const aiChatBodySchema: Schema<AiChatBody> = lazy(() =>
  typedExpandoObject(
    {
      messages: ['messages', array(aiChatMessageSchema)],
      stream: ['stream', optional(boolean())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
