/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AirlinePriceIndex {
  /** Date */
  date?: string;
  /** Price Index */
  priceIndex?: number;
  /** Daily average ticket price. */
  dailyAvgPrice?: number;
  additionalProperties?: Record<string, unknown>;
}

export const airlinePriceIndexSchema: Schema<AirlinePriceIndex> = typedExpandoObject(
  {
    date: ['date', optional(string())],
    priceIndex: ['priceIndex', optional(number())],
    dailyAvgPrice: ['dailyAvgPrice', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
