/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AirlinePriceIndex,
  airlinePriceIndexSchema,
} from './airlinePriceIndex.js';

export interface AirlinePriceIndexData {
  /** Array of price index. */
  data?: AirlinePriceIndex[];
  /** Airline name */
  airline?: string;
  /** From date */
  from?: string;
  /** To date */
  to?: string;
  additionalProperties?: Record<string, unknown>;
}

export const airlinePriceIndexDataSchema: Schema<AirlinePriceIndexData> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(airlinePriceIndexSchema))],
        airline: ['airline', optional(string())],
        from: ['from', optional(string())],
        to: ['to', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
