/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BankBranchData {
  /** Branch ID */
  branchId?: string;
  /** Branch address */
  address?: string;
  /** State */
  state?: string;
  /** Zip code */
  zipCode?: string;
  /** Date opened */
  date?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankBranchDataSchema: Schema<BankBranchData> = typedExpandoObject(
  {
    branchId: ['branchId', optional(string())],
    address: ['address', optional(string())],
    state: ['state', optional(string())],
    zipCode: ['zipCode', optional(string())],
    date: ['date', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
