/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BankBranchData, bankBranchDataSchema } from './bankBranchData.js';

export interface BankBranchRes {
  /** Array of branches. */
  data?: BankBranchData[];
  /** Symbol */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankBranchResSchema: Schema<BankBranchRes> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', optional(array(bankBranchDataSchema))],
      symbol: ['symbol', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
