/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BasicFinancials {
  /** Symbol of the company. */
  symbol?: string;
  /** Metric type. */
  metricType?: string;
  series?: unknown;
  metric?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const basicFinancialsSchema: Schema<BasicFinancials> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    metricType: ['metricType', optional(string())],
    series: ['series', optional(unknown())],
    metric: ['metric', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
