/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BondTickData {
  /** Number of ticks skipped. */
  skip?: bigint;
  /** Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
  count?: bigint;
  /** Total number of ticks for that date. */
  total?: bigint;
  /** List of volume data. */
  v?: number[];
  /** List of price data. */
  p?: number[];
  /** List of yield data. */
  y?: number[];
  /** List of timestamp in UNIX ms. */
  t?: bigint[];
  /** List of values showing the side (Buy/sell) of each trade. List of supported values: <a target="_blank" href="https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing",>here</a> */
  si?: string[];
  /** List of values showing the counterparty of each trade. List of supported values: <a target="_blank" href="https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing",>here</a> */
  cp?: string[];
  /** List of values showing the reporting party of each trade. List of supported values: <a target="_blank" href="https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing",>here</a> */
  rp?: string[];
  /** ATS flag. Y or empty */
  ats?: string[];
  /** List of trade conditions. A comprehensive list of trade conditions code can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing">here</a> */
  c?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const bondTickDataSchema: Schema<BondTickData> = typedExpandoObject(
  {
    skip: ['skip', optional(bigint())],
    count: ['count', optional(bigint())],
    total: ['total', optional(bigint())],
    v: ['v', optional(array(number()))],
    p: ['p', optional(array(number()))],
    y: ['y', optional(array(number()))],
    t: ['t', optional(array(bigint()))],
    si: ['si', optional(array(string()))],
    cp: ['cp', optional(array(string()))],
    rp: ['rp', optional(array(string()))],
    ats: ['ats', optional(array(string()))],
    c: ['c', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
