/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BondCandles {
  /** List of close prices for returned candles. */
  c?: number[];
  /** List of timestamp for returned candles. */
  t?: bigint[];
  /** Status of the response. This field can either be ok or no_data. */
  s?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bondCandlesSchema: Schema<BondCandles> = typedExpandoObject(
  {
    c: ['c', optional(array(number()))],
    t: ['t', optional(array(bigint()))],
    s: ['s', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
