/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BondYieldCurveInfo,
  bondYieldCurveInfoSchema,
} from './bondYieldCurveInfo.js';

export interface BondYieldCurve {
  /** Array of data. */
  data?: BondYieldCurveInfo[];
  /** Bond's code */
  code?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bondYieldCurveSchema: Schema<BondYieldCurve> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', optional(array(bondYieldCurveInfoSchema))],
      code: ['code', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
