/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BondProfile {
  /** ISIN. */
  isin?: string;
  /** Cusip. */
  cusip?: string;
  /** FIGI. */
  figi?: string;
  /** Coupon. */
  coupon?: number;
  /** Period. */
  maturityDate?: string;
  /** Offering price. */
  offeringPrice?: number;
  /** Issue date. */
  issueDate?: string;
  /** Bond type. */
  bondType?: string;
  /** Bond type. */
  debtType?: string;
  /** Industry. */
  industryGroup?: string;
  /** Sub-Industry. */
  industrySubGroup?: string;
  /** Asset. */
  asset?: string;
  /** Asset. */
  assetType?: string;
  /** Dated date. */
  datedDate?: string;
  /** First coupon date. */
  firstCouponDate?: string;
  /** Offering amount. */
  originalOffering?: number;
  /** Outstanding amount. */
  amountOutstanding?: number;
  /** Payment frequency. */
  paymentFrequency?: string;
  /** Security level. */
  securityLevel?: string;
  /** Callable. */
  callable?: boolean;
  /** Coupon type. */
  couponType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const bondProfileSchema: Schema<BondProfile> = typedExpandoObject(
  {
    isin: ['isin', optional(string())],
    cusip: ['cusip', optional(string())],
    figi: ['figi', optional(string())],
    coupon: ['coupon', optional(number())],
    maturityDate: ['maturityDate', optional(string())],
    offeringPrice: ['offeringPrice', optional(number())],
    issueDate: ['issueDate', optional(string())],
    bondType: ['bondType', optional(string())],
    debtType: ['debtType', optional(string())],
    industryGroup: ['industryGroup', optional(string())],
    industrySubGroup: ['industrySubGroup', optional(string())],
    asset: ['asset', optional(string())],
    assetType: ['assetType', optional(string())],
    datedDate: ['datedDate', optional(string())],
    firstCouponDate: ['firstCouponDate', optional(string())],
    originalOffering: ['originalOffering', optional(number())],
    amountOutstanding: ['amountOutstanding', optional(number())],
    paymentFrequency: ['paymentFrequency', optional(string())],
    securityLevel: ['securityLevel', optional(string())],
    callable: ['callable', optional(boolean())],
    couponType: ['couponType', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
