/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BondYieldCurveInfo {
  /** Date of the reading */
  d?: string;
  /** Value */
  v?: number;
  additionalProperties?: Record<string, unknown>;
}

export const bondYieldCurveInfoSchema: Schema<BondYieldCurveInfo> = typedExpandoObject(
  { d: ['d', optional(string())], v: ['v', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
