/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BreakdownItem {
  /** Access number of the report from which the data is sourced. */
  accessNumber?: string;
  breakdown?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const breakdownItemSchema: Schema<BreakdownItem> = typedExpandoObject(
  {
    accessNumber: ['accessNumber', optional(string())],
    breakdown: ['breakdown', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
