/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CapexEstimatesInfo,
  capexEstimatesInfoSchema,
} from './capexEstimatesInfo.js';

export interface CapexEstimates {
  /** List of estimates */
  data?: CapexEstimatesInfo[];
  /** Frequency: annual or quarterly. */
  freq?: string;
  /** Company symbol. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const capexEstimatesSchema: Schema<CapexEstimates> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', optional(array(capexEstimatesInfoSchema))],
      freq: ['freq', optional(string())],
      symbol: ['symbol', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
