/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CapexEstimatesInfo {
  /** Average capex estimates including Finnhub's proprietary estimates. */
  capexAvg?: number;
  /** Highest estimate. */
  capexHigh?: number;
  /** Lowest estimate. */
  capexLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const capexEstimatesInfoSchema: Schema<CapexEstimatesInfo> = typedExpandoObject(
  {
    capexAvg: ['capexAvg', optional(number())],
    capexHigh: ['capexHigh', optional(number())],
    capexLow: ['capexLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
