/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyEsg2 {
  /** Total ESG Score */
  totalEsgScore?: number;
  /** Environment Score */
  environmentScore?: number;
  /** Governance Score */
  governanceScore?: number;
  /** Social Score */
  socialScore?: number;
  data?: unknown;
  /** Period */
  period?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companyEsg2Schema: Schema<CompanyEsg2> = typedExpandoObject(
  {
    totalEsgScore: ['totalESGScore', optional(number())],
    environmentScore: ['environmentScore', optional(number())],
    governanceScore: ['governanceScore', optional(number())],
    socialScore: ['socialScore', optional(number())],
    data: ['data', optional(unknown())],
    period: ['period', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
