/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyProfile {
  /** Company name alias. */
  alias?: string[];
  /** Address of company's headquarter. */
  address?: string;
  /** City of company's headquarter. */
  city?: string;
  /** Country of company's headquarter. */
  country?: string;
  /** Currency used in company filings and financials. */
  currency?: string;
  /** Currency used in Estimates data. */
  estimateCurrency?: string;
  /** Currency used in market capitalization. */
  marketCapCurrency?: string;
  /** CUSIP number. */
  cusip?: string;
  /** Sedol number. */
  sedol?: string;
  /** Company business summary. */
  description?: string;
  /** Listed exchange. */
  exchange?: string;
  /** Industry group. */
  ggroup?: string;
  /** Industry. */
  gind?: string;
  /** Sector. */
  gsector?: string;
  /** Sub-industry. */
  gsubind?: string;
  /** ISIN number. */
  isin?: string;
  /** LEI number. */
  lei?: string;
  /** Investor relations website. */
  irUrl?: string;
  /** NAICS national industry. */
  naicsNationalIndustry?: string;
  /** NAICS industry. */
  naics?: string;
  /** NAICS sector. */
  naicsSector?: string;
  /** NAICS subsector. */
  naicsSubsector?: string;
  /** Company name. */
  name?: string;
  /** Company phone number. */
  phone?: string;
  /** State of company's headquarter. */
  state?: string;
  /** Company symbol/ticker as used on the listed exchange. */
  ticker?: string;
  /** Company website. */
  weburl?: string;
  /** IPO date. */
  ipo?: string;
  /** Market Capitalization. */
  marketCapitalization?: number;
  /** Number of oustanding shares. */
  shareOutstanding?: number;
  /** Number of employee. */
  employeeTotal?: number;
  /** Logo image. */
  logo?: string;
  /** Finnhub industry classification. */
  finnhubIndustry?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companyProfileSchema: Schema<CompanyProfile> = typedExpandoObject(
  {
    alias: ['alias', optional(array(string()))],
    address: ['address', optional(string())],
    city: ['city', optional(string())],
    country: ['country', optional(string())],
    currency: ['currency', optional(string())],
    estimateCurrency: ['estimateCurrency', optional(string())],
    marketCapCurrency: ['marketCapCurrency', optional(string())],
    cusip: ['cusip', optional(string())],
    sedol: ['sedol', optional(string())],
    description: ['description', optional(string())],
    exchange: ['exchange', optional(string())],
    ggroup: ['ggroup', optional(string())],
    gind: ['gind', optional(string())],
    gsector: ['gsector', optional(string())],
    gsubind: ['gsubind', optional(string())],
    isin: ['isin', optional(string())],
    lei: ['lei', optional(string())],
    irUrl: ['irUrl', optional(string())],
    naicsNationalIndustry: ['naicsNationalIndustry', optional(string())],
    naics: ['naics', optional(string())],
    naicsSector: ['naicsSector', optional(string())],
    naicsSubsector: ['naicsSubsector', optional(string())],
    name: ['name', optional(string())],
    phone: ['phone', optional(string())],
    state: ['state', optional(string())],
    ticker: ['ticker', optional(string())],
    weburl: ['weburl', optional(string())],
    ipo: ['ipo', optional(string())],
    marketCapitalization: ['marketCapitalization', optional(number())],
    shareOutstanding: ['shareOutstanding', optional(number())],
    employeeTotal: ['employeeTotal', optional(number())],
    logo: ['logo', optional(string())],
    finnhubIndustry: ['finnhubIndustry', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
