/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyNewsStatistics {
  articlesInLastWeek?: bigint;
  buzz?: number;
  weeklyAverage?: number;
  additionalProperties?: Record<string, unknown>;
}

export const companyNewsStatisticsSchema: Schema<CompanyNewsStatistics> = typedExpandoObject(
  {
    articlesInLastWeek: ['articlesInLastWeek', optional(bigint())],
    buzz: ['buzz', optional(number())],
    weeklyAverage: ['weeklyAverage', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
