/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Company {
  /** Executive name */
  name?: string;
  /** Age */
  age?: bigint;
  /** Title */
  title?: string;
  /** Year first appointed as executive/director of the company */
  since?: string;
  /** Sex */
  sex?: string;
  /** Total compensation */
  compensation?: bigint;
  /** Compensation currency */
  currency?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companySchema: Schema<Company> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    age: ['age', optional(bigint())],
    title: ['title', optional(string())],
    since: ['since', optional(string())],
    sex: ['sex', optional(string())],
    compensation: ['compensation', optional(bigint())],
    currency: ['currency', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
