/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Company, companySchema } from './company.js';

export interface CompanyExecutive {
  /** Company symbol. */
  symbol?: string;
  /** Array of company's executives and members of the Board. */
  executive?: Company[];
  additionalProperties?: Record<string, unknown>;
}

export const companyExecutiveSchema: Schema<CompanyExecutive> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      executive: ['executive', optional(array(companySchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
