/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyEarningsQualityScoreData {
  /** Period */
  period?: string;
  /** Growth Score */
  growth?: number;
  /** Profitability Score */
  profitability?: number;
  /** Cash Generation and Capital Allocation */
  cashGenerationCapitalAllocation?: number;
  /** Leverage Score */
  leverage?: number;
  /** Total Score */
  score?: number;
  /** Letter Score */
  letterScore?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companyEarningsQualityScoreDataSchema: Schema<CompanyEarningsQualityScoreData> = typedExpandoObject(
  {
    period: ['period', optional(string())],
    growth: ['growth', optional(number())],
    profitability: ['profitability', optional(number())],
    cashGenerationCapitalAllocation: [
      'cashGenerationCapitalAllocation',
      optional(number()),
    ],
    leverage: ['leverage', optional(number())],
    score: ['score', optional(number())],
    letterScore: ['letterScore', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
