/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CompanyEarningsQualityScoreData,
  companyEarningsQualityScoreDataSchema,
} from './companyEarningsQualityScoreData.js';

export interface CompanyEarningsQualityScore {
  /** Symbol */
  symbol?: string;
  /** Frequency */
  freq?: string;
  /** Array of earnings quality score. */
  data?: CompanyEarningsQualityScoreData[];
  additionalProperties?: Record<string, unknown>;
}

export const companyEarningsQualityScoreSchema: Schema<CompanyEarningsQualityScore> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        freq: ['freq', optional(string())],
        data: ['data', optional(array(companyEarningsQualityScoreDataSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
