/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyNews {
  /** News category. */
  category?: string;
  /** Published time in UNIX timestamp. */
  datetime?: bigint;
  /** News headline. */
  headline?: string;
  /** News ID. This value can be used for <code>minId</code> params to get the latest news only. */
  id?: bigint;
  /** Thumbnail image URL. */
  image?: string;
  /** Related stocks and companies mentioned in the article. */
  related?: string;
  /** News source. */
  source?: string;
  /** News summary. */
  summary?: string;
  /** URL of the original article. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companyNewsSchema: Schema<CompanyNews> = typedExpandoObject(
  {
    category: ['category', optional(string())],
    datetime: ['datetime', optional(bigint())],
    headline: ['headline', optional(string())],
    id: ['id', optional(bigint())],
    image: ['image', optional(string())],
    related: ['related', optional(string())],
    source: ['source', optional(string())],
    summary: ['summary', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
