/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyProfile2 {
  /** Country of company's headquarter. */
  country?: string;
  /** Currency used in company filings. */
  currency?: string;
  /** Listed exchange. */
  exchange?: string;
  /** Company name. */
  name?: string;
  /** Company symbol/ticker as used on the listed exchange. */
  ticker?: string;
  /** IPO date. */
  ipo?: string;
  /** Market Capitalization. */
  marketCapitalization?: number;
  /** Number of oustanding shares. */
  shareOutstanding?: number;
  /** Logo image. */
  logo?: string;
  /** Company phone number. */
  phone?: string;
  /** Company website. */
  weburl?: string;
  /** Finnhub industry classification. */
  finnhubIndustry?: string;
  additionalProperties?: Record<string, unknown>;
}

export const companyProfile2Schema: Schema<CompanyProfile2> = typedExpandoObject(
  {
    country: ['country', optional(string())],
    currency: ['currency', optional(string())],
    exchange: ['exchange', optional(string())],
    name: ['name', optional(string())],
    ticker: ['ticker', optional(string())],
    ipo: ['ipo', optional(string())],
    marketCapitalization: ['marketCapitalization', optional(number())],
    shareOutstanding: ['shareOutstanding', optional(number())],
    logo: ['logo', optional(string())],
    phone: ['phone', optional(string())],
    weburl: ['weburl', optional(string())],
    finnhubIndustry: ['finnhubIndustry', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
