/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CompanyEsg {
  /** symbol */
  symbol?: string;
  /** Total ESG Score */
  totalEsgScore?: number;
  /** Environment Score */
  environmentScore?: number;
  /** Governance Score */
  governanceScore?: number;
  /** Social Score */
  socialScore?: number;
  data?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const companyEsgSchema: Schema<CompanyEsg> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    totalEsgScore: ['totalESGScore', optional(number())],
    environmentScore: ['environmentScore', optional(number())],
    governanceScore: ['governanceScore', optional(number())],
    socialScore: ['socialScore', optional(number())],
    data: ['data', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
