/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CongressionalTransaction,
  congressionalTransactionSchema,
} from './congressionalTransaction.js';

export interface CongressionalTrading {
  /** Symbol of the company. */
  symbol?: string;
  /** Array of stock trades. */
  data?: CongressionalTransaction[];
  additionalProperties?: Record<string, unknown>;
}

export const congressionalTradingSchema: Schema<CongressionalTrading> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        data: ['data', optional(array(congressionalTransactionSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
