/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CongressionalTransaction {
  /** Transaction amount from. */
  amountFrom?: number;
  /** Transaction amount to. */
  amountTo?: number;
  /** Asset name. */
  assetName?: string;
  /** Filing date. */
  filingDate?: string;
  /** Name of the representative. */
  name?: string;
  /** Owner Type. */
  ownerType?: string;
  /** Position. */
  position?: string;
  /** Symbol. */
  symbol?: string;
  /** Transaction date. */
  transactionDate?: string;
  /** Transaction type <code>Sale</code> or <code>Purchase</code>. */
  transactionType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const congressionalTransactionSchema: Schema<CongressionalTransaction> = typedExpandoObject(
  {
    amountFrom: ['amountFrom', optional(number())],
    amountTo: ['amountTo', optional(number())],
    assetName: ['assetName', optional(string())],
    filingDate: ['filingDate', optional(string())],
    name: ['name', optional(string())],
    ownerType: ['ownerType', optional(string())],
    position: ['position', optional(string())],
    symbol: ['symbol', optional(string())],
    transactionDate: ['transactionDate', optional(string())],
    transactionType: ['transactionType', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
