/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CountryMetadata {
  /** Country name */
  country?: string;
  /** Alpha 2 code */
  code2?: string;
  /** Alpha 3 code */
  code3?: string;
  /** UN code */
  codeNo?: string;
  /** Currency name */
  currency?: string;
  /** Currency code */
  currencyCode?: string;
  /** Region */
  region?: string;
  /** Sub-Region */
  subRegion?: string;
  /** Moody's credit risk rating. */
  rating?: string;
  /** Default spread */
  defaultSpread?: number;
  /** Country risk premium */
  countryRiskPremium?: number;
  /** Equity risk premium */
  equityRiskPremium?: number;
  /** Flag image */
  logo?: string;
  additionalProperties?: Record<string, unknown>;
}

export const countryMetadataSchema: Schema<CountryMetadata> = typedExpandoObject(
  {
    country: ['country', optional(string())],
    code2: ['code2', optional(string())],
    code3: ['code3', optional(string())],
    codeNo: ['codeNo', optional(string())],
    currency: ['currency', optional(string())],
    currencyCode: ['currencyCode', optional(string())],
    region: ['region', optional(string())],
    subRegion: ['subRegion', optional(string())],
    rating: ['rating', optional(string())],
    defaultSpread: ['defaultSpread', optional(number())],
    countryRiskPremium: ['countryRiskPremium', optional(number())],
    equityRiskPremium: ['equityRiskPremium', optional(number())],
    logo: ['logo', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
