/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CovidInfo {
  /** State. */
  state?: string;
  /** Number of confirmed cases. */
  mCase?: number;
  /** Number of confirmed deaths. */
  death?: number;
  /** Updated time. */
  updated?: string;
  additionalProperties?: Record<string, unknown>;
}

export const covidInfoSchema: Schema<CovidInfo> = typedExpandoObject(
  {
    state: ['state', optional(string())],
    mCase: ['case', optional(number())],
    death: ['death', optional(number())],
    updated: ['updated', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
