/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CryptoProfile {
  /** Long name. */
  longName?: string;
  /** Name. */
  name?: string;
  /** Description. */
  description?: string;
  /** Project's website. */
  website?: string;
  /** Market capitalization. */
  marketCap?: number;
  /** Total supply. */
  totalSupply?: number;
  /** Max supply. */
  maxSupply?: number;
  /** Circulating supply. */
  circulatingSupply?: number;
  /** Logo image. */
  logo?: string;
  /** Launch date. */
  launchDate?: string;
  /** Proof type. */
  proofType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cryptoProfileSchema: Schema<CryptoProfile> = typedExpandoObject(
  {
    longName: ['longName', optional(string())],
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    website: ['website', optional(string())],
    marketCap: ['marketCap', optional(number())],
    totalSupply: ['totalSupply', optional(number())],
    maxSupply: ['maxSupply', optional(number())],
    circulatingSupply: ['circulatingSupply', optional(number())],
    logo: ['logo', optional(string())],
    launchDate: ['launchDate', optional(string())],
    proofType: ['proofType', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
