/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CryptoSymbol {
  /** Symbol description */
  description?: string;
  /** Display symbol name. */
  displaySymbol?: string;
  /** Unique symbol used to identify this symbol used in <code>/crypto/candle</code> endpoint. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cryptoSymbolSchema: Schema<CryptoSymbol> = typedExpandoObject(
  {
    description: ['description', optional(string())],
    displaySymbol: ['displaySymbol', optional(string())],
    symbol: ['symbol', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
