/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CryptoCandles {
  /** List of open prices for returned candles. */
  o?: number[];
  /** List of high prices for returned candles. */
  h?: number[];
  /** List of low prices for returned candles. */
  l?: number[];
  /** List of close prices for returned candles. */
  c?: number[];
  /** List of volume data for returned candles. */
  v?: number[];
  /** List of timestamp for returned candles. */
  t?: bigint[];
  /** Status of the response. This field can either be ok or no_data. */
  s?: string;
  additionalProperties?: Record<string, unknown>;
}

export const cryptoCandlesSchema: Schema<CryptoCandles> = typedExpandoObject(
  {
    o: ['o', optional(array(number()))],
    h: ['h', optional(array(number()))],
    l: ['l', optional(array(number()))],
    c: ['c', optional(array(number()))],
    v: ['v', optional(array(number()))],
    t: ['t', optional(array(bigint()))],
    s: ['s', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
