/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Development {
  /** Company symbol. */
  symbol?: string;
  /** Published time in <code>YYYY-MM-DD HH:MM:SS</code> format. */
  datetime?: string;
  /** Development headline. */
  headline?: string;
  /** Development description. */
  description?: string;
  /** URL. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const developmentSchema: Schema<Development> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    datetime: ['datetime', optional(string())],
    headline: ['headline', optional(string())],
    description: ['description', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
