/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Dividends2Info, dividends2InfoSchema } from './dividends2Info.js';

export interface Dividends2 {
  /** Symbol */
  symbol?: string;
  data?: Dividends2Info[];
  additionalProperties?: Record<string, unknown>;
}

export const dividends2Schema: Schema<Dividends2> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(dividends2InfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
