/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Dividends2Info {
  /** Ex-Dividend date. */
  exDate?: string;
  /** Amount in local currency. */
  amount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const dividends2InfoSchema: Schema<Dividends2Info> = typedExpandoObject(
  {
    exDate: ['exDate', optional(string())],
    amount: ['amount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
