/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Dividends {
  /** Symbol. */
  symbol?: string;
  /** Ex-Dividend date. */
  date?: string;
  /** Amount in local currency. */
  amount?: number;
  /** Adjusted dividend. */
  adjustedAmount?: number;
  /** Pay date. */
  payDate?: string;
  /** Record date. */
  recordDate?: string;
  /** Declaration date. */
  declarationDate?: string;
  /** Currency. */
  currency?: string;
  /**
   * <p>Dividend frequency. Can be 1 of the following values:</p><ul>
   * <li><code>0: Annually</code></li>
   * <li><code>1: Monthly</code></li>
   * <li><code>2: Quarterly</code></li>
   * <li><code>3: Semi-annually</code></li>
   * <li><code>4: Other/Unknown</code></li>
   * <li><code>5: Bimonthly</code></li>
   * <li><code>6: Trimesterly</code></li>
   * <li><code>7: Weekly</code></li>
   * </ul>
   */
  freq?: string;
  additionalProperties?: Record<string, unknown>;
}

export const dividendsSchema: Schema<Dividends> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    date: ['date', optional(string())],
    amount: ['amount', optional(number())],
    adjustedAmount: ['adjustedAmount', optional(number())],
    payDate: ['payDate', optional(string())],
    recordDate: ['recordDate', optional(string())],
    declarationDate: ['declarationDate', optional(string())],
    currency: ['currency', optional(string())],
    freq: ['freq', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
