/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExcerptResponse, excerptResponseSchema } from './excerptResponse.js';

export interface DocumentResponse {
  /** AlphaResearch internal document id. */
  documentId?: string;
  /** Title for this document. */
  title?: string;
  /** Number of hit in this document */
  hits?: string;
  /** Link to render this document */
  url?: string;
  /** Format of this document (can be html or pdf) */
  format?: string;
  /** Highlighted excerpts for this document */
  excerpts?: ExcerptResponse[];
  additionalProperties?: Record<string, unknown>;
}

export const documentResponseSchema: Schema<DocumentResponse> = lazy(() =>
  typedExpandoObject(
    {
      documentId: ['documentId', optional(string())],
      title: ['title', optional(string())],
      hits: ['hits', optional(string())],
      url: ['url', optional(string())],
      format: ['format', optional(string())],
      excerpts: ['excerpts', optional(array(excerptResponseSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
