/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DpsEstimatesInfo,
  dpsEstimatesInfoSchema,
} from './dpsEstimatesInfo.js';

export interface DpsEstimates {
  /** List of estimates */
  data?: DpsEstimatesInfo[];
  /** Frequency: annual or quarterly. */
  freq?: string;
  /** Company symbol. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const dpsEstimatesSchema: Schema<DpsEstimates> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', optional(array(dpsEstimatesInfoSchema))],
      freq: ['freq', optional(string())],
      symbol: ['symbol', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
