/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DpsEstimatesInfo {
  /** Average DPS estimates including Finnhub's proprietary estimates. */
  dpsAvg?: number;
  /** Highest estimate. */
  dpsHigh?: number;
  /** Lowest estimate. */
  dpsLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const dpsEstimatesInfoSchema: Schema<DpsEstimatesInfo> = typedExpandoObject(
  {
    dpsAvg: ['dpsAvg', optional(number())],
    dpsHigh: ['dpsHigh', optional(number())],
    dpsLow: ['dpsLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
