/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EarningRelease {
  /** Symbol. */
  symbol?: string;
  /** Date. */
  date?: string;
  /** Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>). */
  hour?: string;
  /** Earnings year. */
  year?: bigint;
  /** Earnings quarter. */
  quarter?: bigint;
  /** EPS estimate. */
  epsEstimate?: number;
  /** EPS actual. */
  epsActual?: number;
  /** Revenue estimate including Finnhub's proprietary estimates. */
  revenueEstimate?: number;
  /** Revenue actual. */
  revenueActual?: number;
  additionalProperties?: Record<string, unknown>;
}

export const earningReleaseSchema: Schema<EarningRelease> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    date: ['date', optional(string())],
    hour: ['hour', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
    epsEstimate: ['epsEstimate', optional(number())],
    epsActual: ['epsActual', optional(number())],
    revenueEstimate: ['revenueEstimate', optional(number())],
    revenueActual: ['revenueActual', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
