/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EarningsCallLiveResult {
  /** Symbol. */
  symbol?: string;
  /** Event name. */
  event?: string;
  /** Date time in UTC. */
  time?: string;
  /** Earnings year. */
  year?: bigint;
  /** Earnings quarter. */
  quarter?: bigint;
  /** Live audio streaming file. */
  liveAudio?: string;
  /** Recoding in mp3 format. */
  recording?: string;
  additionalProperties?: Record<string, unknown>;
}

export const earningsCallLiveResultSchema: Schema<EarningsCallLiveResult> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    event: ['event', optional(string())],
    time: ['time', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
    liveAudio: ['liveAudio', optional(string())],
    recording: ['recording', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
