/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EarningResult {
  /** Actual earning result. */
  actual?: number;
  /** Estimated earning. */
  estimate?: number;
  /** Surprise - The difference between actual and estimate. */
  surprise?: number;
  /** Surprise percent. */
  surprisePercent?: number;
  /** Reported period. */
  period?: string;
  /** Company symbol. */
  symbol?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const earningResultSchema: Schema<EarningResult> = typedExpandoObject(
  {
    actual: ['actual', optional(number())],
    estimate: ['estimate', optional(number())],
    surprise: ['surprise', optional(number())],
    surprisePercent: ['surprisePercent', optional(number())],
    period: ['period', optional(string())],
    symbol: ['symbol', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
