/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EarningRelease, earningReleaseSchema } from './earningRelease.js';

export interface EarningsCalendar {
  /** Array of earnings release. */
  earningsCalendar?: EarningRelease[];
  additionalProperties?: Record<string, unknown>;
}

export const earningsCalendarSchema: Schema<EarningsCalendar> = lazy(() =>
  typedExpandoObject(
    {
      earningsCalendar: [
        'earningsCalendar',
        optional(array(earningReleaseSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
