/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  StockTranscripts,
  stockTranscriptsSchema,
} from './stockTranscripts.js';

export interface EarningsCallTranscriptsList {
  /** Company symbol. */
  symbol?: string;
  /** Array of transcripts' metadata */
  transcripts?: StockTranscripts[];
  additionalProperties?: Record<string, unknown>;
}

export const earningsCallTranscriptsListSchema: Schema<EarningsCallTranscriptsList> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        transcripts: ['transcripts', optional(array(stockTranscriptsSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
