/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TranscriptContent,
  transcriptContentSchema,
} from './transcriptContent.js';
import {
  TranscriptParticipant,
  transcriptParticipantSchema,
} from './transcriptParticipant.js';

export interface EarningsCallTranscripts {
  /** Company symbol. */
  symbol?: string;
  /** Transcript content. */
  transcript?: TranscriptContent[];
  /** Participant list */
  participant?: TranscriptParticipant[];
  /** Audio link. */
  audio?: string;
  /** Transcript's ID. */
  id?: string;
  /** Title. */
  title?: string;
  /** Time of the event. */
  time?: string;
  /** Year of earnings result in the case of earnings call transcript. */
  year?: bigint;
  /** Quarter of earnings result in the case of earnings call transcript. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const earningsCallTranscriptsSchema: Schema<EarningsCallTranscripts> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        transcript: ['transcript', optional(array(transcriptContentSchema))],
        participant: [
          'participant',
          optional(array(transcriptParticipantSchema)),
        ],
        audio: ['audio', optional(string())],
        id: ['id', optional(string())],
        title: ['title', optional(string())],
        time: ['time', optional(string())],
        year: ['year', optional(bigint())],
        quarter: ['quarter', optional(bigint())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
