/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EarningsEstimatesInfo {
  /** Average EPS estimates including Finnhub's proprietary estimates. */
  epsAvg?: number;
  /** Highest estimate. */
  epsHigh?: number;
  /** Lowest estimate. */
  epsLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const earningsEstimatesInfoSchema: Schema<EarningsEstimatesInfo> = typedExpandoObject(
  {
    epsAvg: ['epsAvg', optional(number())],
    epsHigh: ['epsHigh', optional(number())],
    epsLow: ['epsLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
