/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EarningsCallLiveResult,
  earningsCallLiveResultSchema,
} from './earningsCallLiveResult.js';

export interface EarningsCallLive {
  /** Array of earnings call events that support live streaming. */
  event?: EarningsCallLiveResult[];
  additionalProperties?: Record<string, unknown>;
}

export const earningsCallLiveSchema: Schema<EarningsCallLive> = lazy(() =>
  typedExpandoObject(
    { event: ['event', optional(array(earningsCallLiveResultSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
