/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EbitEstimatesInfo {
  /** Average EBIT estimates including Finnhub's proprietary estimates. */
  ebitAvg?: number;
  /** Highest estimate. */
  ebitHigh?: number;
  /** Lowest estimate. */
  ebitLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const ebitEstimatesInfoSchema: Schema<EbitEstimatesInfo> = typedExpandoObject(
  {
    ebitAvg: ['ebitAvg', optional(number())],
    ebitHigh: ['ebitHigh', optional(number())],
    ebitLow: ['ebitLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
