/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EbitdaEstimatesInfo {
  /** Average EBITDA estimates including Finnhub's proprietary estimates. */
  ebitdaAvg?: number;
  /** Highest estimate. */
  ebitdaHigh?: number;
  /** Lowest estimate. */
  ebitdaLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const ebitdaEstimatesInfoSchema: Schema<EbitdaEstimatesInfo> = typedExpandoObject(
  {
    ebitdaAvg: ['ebitdaAvg', optional(number())],
    ebitdaHigh: ['ebitdaHigh', optional(number())],
    ebitdaLow: ['ebitdaLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
