/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EconomicDataInfo {
  /** Date of the reading */
  date?: string;
  /** Value */
  value?: number;
  additionalProperties?: Record<string, unknown>;
}

export const economicDataInfoSchema: Schema<EconomicDataInfo> = typedExpandoObject(
  { date: ['date', optional(string())], value: ['value', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
