/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EconomicCode {
  /** Finnhub economic code used to get historical data */
  code?: string;
  /** Country */
  country?: string;
  /** Indicator name */
  name?: string;
  /** Unit */
  unit?: string;
  additionalProperties?: Record<string, unknown>;
}

export const economicCodeSchema: Schema<EconomicCode> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    country: ['country', optional(string())],
    name: ['name', optional(string())],
    unit: ['unit', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
