/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EconomicEvent {
  /** Actual release */
  actual?: number;
  /** Previous release */
  prev?: number;
  /** Country */
  country?: string;
  /** Unit */
  unit?: string;
  /** Estimate */
  estimate?: number;
  /** Event */
  event?: string;
  /** Impact level */
  impact?: string;
  /** Release time */
  time?: string;
  additionalProperties?: Record<string, unknown>;
}

export const economicEventSchema: Schema<EconomicEvent> = typedExpandoObject(
  {
    actual: ['actual', optional(number())],
    prev: ['prev', optional(number())],
    country: ['country', optional(string())],
    unit: ['unit', optional(string())],
    estimate: ['estimate', optional(number())],
    event: ['event', optional(string())],
    impact: ['impact', optional(string())],
    time: ['time', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
