/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EconomicEvent, economicEventSchema } from './economicEvent.js';

export interface EconomicCalendar {
  /** Array of economic events. */
  economicCalendar?: EconomicEvent[];
  additionalProperties?: Record<string, unknown>;
}

export const economicCalendarSchema: Schema<EconomicCalendar> = lazy(() =>
  typedExpandoObject(
    {
      economicCalendar: [
        'economicCalendar',
        optional(array(economicEventSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
