/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EconomicDataInfo,
  economicDataInfoSchema,
} from './economicDataInfo.js';

export interface EconomicData {
  /** Array of economic data for requested code. */
  data?: EconomicDataInfo[];
  /** Finnhub economic code */
  code?: string;
  additionalProperties?: Record<string, unknown>;
}

export const economicDataSchema: Schema<EconomicData> = lazy(() =>
  typedExpandoObject(
    {
      data: ['data', optional(array(economicDataInfoSchema))],
      code: ['code', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
