/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EtfAllocationData {
  /** Percentage of stocks classified as Large Blend. */
  largeBlend?: number;
  /** Percentage of stocks classified as Large Growth. */
  largeGrowth?: number;
  /** Percentage of stocks classified as Large Value. */
  largeValue?: number;
  /** Percentage of stocks classified as Mid-cap Blend. */
  midBlend?: number;
  /** Percentage of stocks classified as Mid-cap Growth. */
  midGrowth?: number;
  /** Percentage of stocks classified as Mid-cap Value. */
  midValue?: number;
  /** Percentage of stocks classified as Small-cap Blend. */
  smallBlend?: number;
  /** Percentage of stocks classified as Small-cap Growth. */
  smallGrowth?: number;
  /** Percentage of stocks classified as Small-cap Value. */
  smallValue?: number;
  additionalProperties?: Record<string, unknown>;
}

export const etfAllocationDataSchema: Schema<EtfAllocationData> = typedExpandoObject(
  {
    largeBlend: ['largeBlend', optional(number())],
    largeGrowth: ['largeGrowth', optional(number())],
    largeValue: ['largeValue', optional(number())],
    midBlend: ['midBlend', optional(number())],
    midGrowth: ['midGrowth', optional(number())],
    midValue: ['midValue', optional(number())],
    smallBlend: ['smallBlend', optional(number())],
    smallGrowth: ['smallGrowth', optional(number())],
    smallValue: ['smallValue', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
