/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EtfHoldingsData {
  /** Symbol description */
  symbol?: string;
  /** Security name */
  name?: string;
  /** ISIN. */
  isin?: string;
  /** CUSIP. */
  cusip?: string;
  /** Number of shares owned by the ETF. */
  share?: number;
  /** Portfolio's percent */
  percent?: number;
  /** Market value */
  value?: number;
  /** Asset type. Can be 1 of the following values: <code>Equity</code>, <code>ETP</code>, <code>Fund</code>, <code>Bond</code>, <code>Other</code> or empty. */
  assetType?: string;
  additionalProperties?: Record<string, unknown>;
}

export const etfHoldingsDataSchema: Schema<EtfHoldingsData> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    name: ['name', optional(string())],
    isin: ['isin', optional(string())],
    cusip: ['cusip', optional(string())],
    share: ['share', optional(number())],
    percent: ['percent', optional(number())],
    value: ['value', optional(number())],
    assetType: ['assetType', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
