/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EtfProfileData {
  /** Name */
  name?: string;
  /** Asset Class. */
  assetClass?: string;
  /** Investment Segment. */
  investmentSegment?: string;
  /** AUM. */
  aum?: number;
  /** NAV. */
  nav?: number;
  /** NAV currency. */
  navCurrency?: string;
  /** Expense ratio. For non-US funds, this is the <a href="https://www.esma.europa.eu/sites/default/files/library/2015/11/09_1028_final_kid_ongoing_charges_methodology_for_publication_u_2_.pdf" target="_blank">KID ongoing charges<a/>. */
  expenseRatio?: number;
  /** Tracking Index. */
  trackingIndex?: string;
  /** ETF issuer. */
  etfCompany?: string;
  /** ETF domicile. */
  domicile?: string;
  /** Inception date. */
  inceptionDate?: string;
  /** ETF's website. */
  website?: string;
  /** Logo. */
  logo?: string;
  /** ISIN. */
  isin?: string;
  /** CUSIP. */
  cusip?: string;
  /** P/E. */
  priceToEarnings?: number;
  /** P/B. */
  priceToBook?: number;
  /** 30-day average volume. */
  avgVolume?: number;
  /** ETF's description. */
  description?: string;
  /** Whether the ETF is inverse */
  isInverse?: boolean;
  /** Whether the ETF is leveraged */
  isLeveraged?: boolean;
  /** Leverage factor. */
  leverageFactor?: number;
  /** Dividend yield. */
  dividendYield?: number;
  additionalProperties?: Record<string, unknown>;
}

export const etfProfileDataSchema: Schema<EtfProfileData> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    assetClass: ['assetClass', optional(string())],
    investmentSegment: ['investmentSegment', optional(string())],
    aum: ['aum', optional(number())],
    nav: ['nav', optional(number())],
    navCurrency: ['navCurrency', optional(string())],
    expenseRatio: ['expenseRatio', optional(number())],
    trackingIndex: ['trackingIndex', optional(string())],
    etfCompany: ['etfCompany', optional(string())],
    domicile: ['domicile', optional(string())],
    inceptionDate: ['inceptionDate', optional(string())],
    website: ['website', optional(string())],
    logo: ['logo', optional(string())],
    isin: ['isin', optional(string())],
    cusip: ['cusip', optional(string())],
    priceToEarnings: ['priceToEarnings', optional(number())],
    priceToBook: ['priceToBook', optional(number())],
    avgVolume: ['avgVolume', optional(number())],
    description: ['description', optional(string())],
    isInverse: ['isInverse', optional(boolean())],
    isLeveraged: ['isLeveraged', optional(boolean())],
    leverageFactor: ['leverageFactor', optional(number())],
    dividendYield: ['dividendYield', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
