/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EtfSectorExposureData,
  etfSectorExposureDataSchema,
} from './etfSectorExposureData.js';

export interface EtFsSectorExposure {
  /** ETF symbol. */
  symbol?: string;
  /** Array of industries and exposure levels. */
  sectorExposure?: EtfSectorExposureData[];
  additionalProperties?: Record<string, unknown>;
}

export const etFsSectorExposureSchema: Schema<EtFsSectorExposure> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      sectorExposure: [
        'sectorExposure',
        optional(array(etfSectorExposureDataSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
