/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EtfCountryExposureData,
  etfCountryExposureDataSchema,
} from './etfCountryExposureData.js';

export interface EtFsCountryExposure {
  /** ETF symbol. */
  symbol?: string;
  /** Array of countries and and exposure levels. */
  countryExposure?: EtfCountryExposureData[];
  additionalProperties?: Record<string, unknown>;
}

export const etFsCountryExposureSchema: Schema<EtFsCountryExposure> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      countryExposure: [
        'countryExposure',
        optional(array(etfCountryExposureDataSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
