/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EtfAllocationData,
  etfAllocationDataSchema,
} from './etfAllocationData.js';

export interface EtFsAllocation {
  /** ETF symbol. */
  symbol?: string;
  data?: EtfAllocationData;
  additionalProperties?: Record<string, unknown>;
}

export const etFsAllocationSchema: Schema<EtFsAllocation> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(etfAllocationDataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
