/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EtfHoldingsData, etfHoldingsDataSchema } from './etfHoldingsData.js';

export interface EtFsHoldings {
  /** ETF symbol. */
  symbol?: string;
  /** Holdings update date. */
  atDate?: string;
  /** Number of holdings. */
  numberOfHoldings?: bigint;
  /** Array of holdings. */
  holdings?: EtfHoldingsData[];
  additionalProperties?: Record<string, unknown>;
}

export const etFsHoldingsSchema: Schema<EtFsHoldings> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      atDate: ['atDate', optional(string())],
      numberOfHoldings: ['numberOfHoldings', optional(bigint())],
      holdings: ['holdings', optional(array(etfHoldingsDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
