/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EtfSectorExposureData {
  /** Industry */
  industry?: string;
  /** Percent of exposure. */
  exposure?: number;
  additionalProperties?: Record<string, unknown>;
}

export const etfSectorExposureDataSchema: Schema<EtfSectorExposureData> = typedExpandoObject(
  {
    industry: ['industry', optional(string())],
    exposure: ['exposure', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
