/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EtfProfileData, etfProfileDataSchema } from './etfProfileData.js';

export interface EtFsProfile {
  /** Symbol. */
  symbol?: string;
  profile?: EtfProfileData;
  additionalProperties?: Record<string, unknown>;
}

export const etFsProfileSchema: Schema<EtFsProfile> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      profile: ['profile', optional(etfProfileDataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
