/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExcerptResponse {
  /** Highlighted content */
  content?: string;
  /** Location of the content in the rendered document */
  snippetId?: string;
  /** Start offset of highlighted content */
  startOffset?: string;
  /** End offset of highlighted content */
  endOffset?: string;
  additionalProperties?: Record<string, unknown>;
}

export const excerptResponseSchema: Schema<ExcerptResponse> = typedExpandoObject(
  {
    content: ['content', optional(string())],
    snippetId: ['snippetId', optional(string())],
    startOffset: ['startOffset', optional(string())],
    endOffset: ['endOffset', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
