/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FcfEstimatesInfo {
  /** Average FCF estimates including Finnhub's proprietary estimates. */
  fcfAvg?: number;
  /** Highest estimate. */
  fcfHigh?: number;
  /** Lowest estimate. */
  fcfLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const fcfEstimatesInfoSchema: Schema<FcfEstimatesInfo> = typedExpandoObject(
  {
    fcfAvg: ['fcfAvg', optional(number())],
    fcfHigh: ['fcfHigh', optional(number())],
    fcfLow: ['fcfLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
