/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FdaComitteeMeeting {
  /** Start time of the event in EST. */
  fromDate?: string;
  /** End time of the event in EST. */
  toDate?: string;
  /** Event's description. */
  eventDescription?: string;
  /** URL. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fdaComitteeMeetingSchema: Schema<FdaComitteeMeeting> = typedExpandoObject(
  {
    fromDate: ['fromDate', optional(string())],
    toDate: ['toDate', optional(string())],
    eventDescription: ['eventDescription', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
