/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filing {
  /** Access number. */
  accessNumber?: string;
  /** Symbol. */
  symbol?: string;
  /** CIK. */
  cik?: string;
  /** Form type. */
  form?: string;
  /** Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
  filedDate?: string;
  /** Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
  acceptedDate?: string;
  /** Report's URL. */
  reportUrl?: string;
  /** Filing's URL. */
  filingUrl?: string;
  additionalProperties?: Record<string, unknown>;
}

export const filingSchema: Schema<Filing> = typedExpandoObject(
  {
    accessNumber: ['accessNumber', optional(string())],
    symbol: ['symbol', optional(string())],
    cik: ['cik', optional(string())],
    form: ['form', optional(string())],
    filedDate: ['filedDate', optional(string())],
    acceptedDate: ['acceptedDate', optional(string())],
    reportUrl: ['reportUrl', optional(string())],
    filingUrl: ['filingUrl', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
