/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FilingSentiment {
  /** % of negative words in the filing. */
  negative?: number;
  /** % of positive words in the filing. */
  positive?: number;
  /** % of polarity words in the filing. */
  polarity?: number;
  /** % of litigious words in the filing. */
  litigious?: number;
  /** % of uncertainty words in the filing. */
  uncertainty?: number;
  /** % of constraining words in the filing. */
  constraining?: number;
  /** % of modal-weak words in the filing. */
  modalWeak?: number;
  /** % of modal-strong words in the filing. */
  modalStrong?: number;
  /** % of modal-moderate words in the filing. */
  modalModerate?: number;
  additionalProperties?: Record<string, unknown>;
}

export const filingSentimentSchema: Schema<FilingSentiment> = typedExpandoObject(
  {
    negative: ['negative', optional(number())],
    positive: ['positive', optional(number())],
    polarity: ['polarity', optional(number())],
    litigious: ['litigious', optional(number())],
    uncertainty: ['uncertainty', optional(number())],
    constraining: ['constraining', optional(number())],
    modalWeak: ['modal-weak', optional(number())],
    modalStrong: ['modal-strong', optional(number())],
    modalModerate: ['modal-moderate', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
