/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FinancialStatements {
  /** Symbol of the company. */
  symbol?: string;
  /** An array of map of key, value pairs containing the data for each period. */
  financials?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export const financialStatementsSchema: Schema<FinancialStatements> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    financials: ['financials', optional(array(unknown()))],
  },
  'additionalProperties',
  optional(unknown())
);
