/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Report, reportSchema } from './report.js';

export interface FinancialsAsReported {
  /** Symbol */
  symbol?: string;
  /** CIK */
  cik?: string;
  /** Array of filings. */
  data?: Report[];
  additionalProperties?: Record<string, unknown>;
}

export const financialsAsReportedSchema: Schema<FinancialsAsReported> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        cik: ['cik', optional(string())],
        data: ['data', optional(array(reportSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
