/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Forexrates {
  /** Base currency. */
  base?: string;
  quote?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const forexratesSchema: Schema<Forexrates> = typedExpandoObject(
  { base: ['base', optional(string())], quote: ['quote', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
