/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FundOwnershipInfo {
  /** Investor's name. */
  name?: string;
  /** Number of shares held by the investor. */
  share?: bigint;
  /** Number of share changed (net buy or sell) from the last period. */
  change?: bigint;
  /** Filing date. */
  filingDate?: string;
  /** Percent of the fund's portfolio comprised of the company's share. */
  portfolioPercent?: number;
  additionalProperties?: Record<string, unknown>;
}

export const fundOwnershipInfoSchema: Schema<FundOwnershipInfo> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    share: ['share', optional(bigint())],
    change: ['change', optional(bigint())],
    filingDate: ['filingDate', optional(string())],
    portfolioPercent: ['portfolioPercent', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
