/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  FundOwnershipInfo,
  fundOwnershipInfoSchema,
} from './fundOwnershipInfo.js';

export interface FundOwnership {
  /** Symbol of the company. */
  symbol?: string;
  /** Array of investors with detailed information about their holdings. */
  ownership?: FundOwnershipInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const fundOwnershipSchema: Schema<FundOwnership> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      ownership: ['ownership', optional(array(fundOwnershipInfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
