/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GrossIncomeEstimatesInfo,
  grossIncomeEstimatesInfoSchema,
} from './grossIncomeEstimatesInfo.js';

export interface GrossIncomeEstimates {
  /** List of estimates */
  data?: GrossIncomeEstimatesInfo[];
  /** Frequency: annual or quarterly. */
  freq?: string;
  /** Company symbol. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const grossIncomeEstimatesSchema: Schema<GrossIncomeEstimates> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(grossIncomeEstimatesInfoSchema))],
        freq: ['freq', optional(string())],
        symbol: ['symbol', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
