/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GrossIncomeEstimatesInfo {
  /** Average gross income estimates including Finnhub's proprietary estimates. */
  grossIncomeAvg?: number;
  /** Highest estimate. */
  grossIncomeHigh?: number;
  /** Lowest estimate. */
  grossIncomeLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const grossIncomeEstimatesInfoSchema: Schema<GrossIncomeEstimatesInfo> = typedExpandoObject(
  {
    grossIncomeAvg: ['grossIncomeAvg', optional(number())],
    grossIncomeHigh: ['grossIncomeHigh', optional(number())],
    grossIncomeLow: ['grossIncomeLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
