/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface HistoricalNbbo {
  /** Symbol. */
  s?: string;
  /** Number of ticks skipped. */
  skip?: bigint;
  /** Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
  count?: bigint;
  /** Total number of ticks for that date. */
  total?: bigint;
  /** List of Ask volume data. */
  av?: number[];
  /** List of Ask price data. */
  a?: number[];
  /** List of venues/exchanges - Ask price. A list of exchange codes can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing",>here</a> */
  ax?: string[];
  /** List of Bid volume data. */
  bv?: number[];
  /** List of Bid price data. */
  b?: number[];
  /** List of venues/exchanges - Bid price. A list of exchange codes can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing",>here</a> */
  bx?: string[];
  /** List of timestamp in UNIX ms. */
  t?: bigint[];
  /** List of quote conditions. A comprehensive list of quote conditions code can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1iiA6e7Osdtai0oPMOUzgAIKXCsay89dFDmsegz6OpEg/edit?usp=sharing">here</a> */
  c?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const historicalNbboSchema: Schema<HistoricalNbbo> = typedExpandoObject(
  {
    s: ['s', optional(string())],
    skip: ['skip', optional(bigint())],
    count: ['count', optional(bigint())],
    total: ['total', optional(bigint())],
    av: ['av', optional(array(number()))],
    a: ['a', optional(array(number()))],
    ax: ['ax', optional(array(string()))],
    bv: ['bv', optional(array(number()))],
    b: ['b', optional(array(number()))],
    bx: ['bx', optional(array(string()))],
    t: ['t', optional(array(bigint()))],
    c: ['c', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
