/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CompanyEsg2, companyEsg2Schema } from './companyEsg2.js';

export interface HistoricalCompanyEsg {
  /** symbol */
  symbol?: string;
  /** Historical ESG data points. */
  data?: CompanyEsg2[];
  additionalProperties?: Record<string, unknown>;
}

export const historicalCompanyEsgSchema: Schema<HistoricalCompanyEsg> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        data: ['data', optional(array(companyEsg2Schema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
