/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MarketCapData, marketCapDataSchema } from './marketCapData.js';

export interface HistoricalMarketCapData {
  /** Array of market data. */
  data?: MarketCapData[];
  /** Symbol */
  symbol?: string;
  /** Currency */
  currency?: string;
  additionalProperties?: Record<string, unknown>;
}

export const historicalMarketCapDataSchema: Schema<HistoricalMarketCapData> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(marketCapDataSchema))],
        symbol: ['symbol', optional(string())],
        currency: ['currency', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
