/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EmployeeCount, employeeCountSchema } from './employeeCount.js';

export interface HistoricalEmployeeCount {
  /** Array of market data. */
  data?: EmployeeCount[];
  /** Symbol */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const historicalEmployeeCountSchema: Schema<HistoricalEmployeeCount> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(employeeCountSchema))],
        symbol: ['symbol', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
