/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IndexHistoricalConstituent {
  /** Symbol */
  symbol?: string;
  /** <code>add</code> or <code>remove</code>. */
  action?: string;
  /** Date of joining or leaving the index. */
  date?: string;
  additionalProperties?: Record<string, unknown>;
}

export const indexHistoricalConstituentSchema: Schema<IndexHistoricalConstituent> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    action: ['action', optional(string())],
    date: ['date', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
