/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  IndexHistoricalConstituent,
  indexHistoricalConstituentSchema,
} from './indexHistoricalConstituent.js';

export interface IndicesHistoricalConstituents {
  /** Index's symbol. */
  symbol?: string;
  /** Array of historical constituents. */
  historicalConstituents?: IndexHistoricalConstituent[];
  additionalProperties?: Record<string, unknown>;
}

export const indicesHistoricalConstituentsSchema: Schema<IndicesHistoricalConstituents> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        historicalConstituents: [
          'historicalConstituents',
          optional(array(indexHistoricalConstituentSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
