/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  IndicesConstituentsBreakdown,
  indicesConstituentsBreakdownSchema,
} from './indicesConstituentsBreakdown.js';

export interface IndicesConstituents {
  /** Index's symbol. */
  symbol?: string;
  /** Array of constituents. */
  constituents?: string[];
  /** Array of constituents' details. */
  constituentsBreakdown?: IndicesConstituentsBreakdown[];
  additionalProperties?: Record<string, unknown>;
}

export const indicesConstituentsSchema: Schema<IndicesConstituents> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      constituents: ['constituents', optional(array(string()))],
      constituentsBreakdown: [
        'constituentsBreakdown',
        optional(array(indicesConstituentsBreakdownSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
