/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IndicesConstituentsBreakdown {
  /** Symbol. */
  symbol?: string;
  /** Name. */
  name?: string;
  /** ISIN. */
  isin?: string;
  /** Cusip. */
  cusip?: string;
  /** Global Share Class FIGI. */
  shareClassFigi?: string;
  /** Weight. */
  weight?: number;
  additionalProperties?: Record<string, unknown>;
}

export const indicesConstituentsBreakdownSchema: Schema<IndicesConstituentsBreakdown> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    name: ['name', optional(string())],
    isin: ['isin', optional(string())],
    cusip: ['cusip', optional(string())],
    shareClassFigi: ['shareClassFIGI', optional(string())],
    weight: ['weight', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
