/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Indicator {
  /** Number of buy signals */
  buy?: bigint;
  /** Number of neutral signals */
  neutral?: bigint;
  /** Number of sell signals */
  sell?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const indicatorSchema: Schema<Indicator> = typedExpandoObject(
  {
    buy: ['buy', optional(bigint())],
    neutral: ['neutral', optional(bigint())],
    sell: ['sell', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
