/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InFilingSearchBody {
  /** Search query */
  query: string;
  /** Filing Id to search */
  filingId: string;
  additionalProperties?: Record<string, unknown>;
}

export const inFilingSearchBodySchema: Schema<InFilingSearchBody> = typedExpandoObject(
  { query: ['query', string()], filingId: ['filingId', string()] },
  'additionalProperties',
  optional(unknown())
);
