/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DocumentResponse,
  documentResponseSchema,
} from './documentResponse.js';

export interface InFilingResponse {
  /** Filing Id in Alpharesearch platform */
  filingId?: string;
  /** Filing title */
  title?: string;
  /** Id of the entity submitted the filing */
  filerId?: string;
  /** List of symbol associate with this filing */
  symbol?: unknown;
  /** Filer name */
  name?: string;
  /** Date the filing is submitted. */
  acceptanceDate?: string;
  /** Date the filing is make available to the public */
  filedDate?: string;
  /** Date as which the filing is reported */
  reportDate?: string;
  /** Filing Form */
  form?: string;
  /** Amendment */
  amend?: boolean;
  /** Filing Source */
  source?: string;
  /** Estimate number of page when printing */
  pageCount?: number;
  /** Number of document in this filing */
  documentCount?: number;
  /** Document for this filing. */
  documents?: DocumentResponse[];
  additionalProperties?: Record<string, unknown>;
}

export const inFilingResponseSchema: Schema<InFilingResponse> = lazy(() =>
  typedExpandoObject(
    {
      filingId: ['filingId', optional(string())],
      title: ['title', optional(string())],
      filerId: ['filerId', optional(string())],
      symbol: ['symbol', optional(unknown())],
      name: ['name', optional(string())],
      acceptanceDate: ['acceptanceDate', optional(string())],
      filedDate: ['filedDate', optional(string())],
      reportDate: ['reportDate', optional(string())],
      form: ['form', optional(string())],
      amend: ['amend', optional(boolean())],
      source: ['source', optional(string())],
      pageCount: ['pageCount', optional(number())],
      documentCount: ['documentCount', optional(number())],
      documents: ['documents', optional(array(documentResponseSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
