/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InsiderSentimentsData,
  insiderSentimentsDataSchema,
} from './insiderSentimentsData.js';

export interface InsiderSentiments {
  /** Symbol of the company. */
  symbol?: string;
  /** Array of sentiment data. */
  data?: InsiderSentimentsData[];
  additionalProperties?: Record<string, unknown>;
}

export const insiderSentimentsSchema: Schema<InsiderSentiments> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(insiderSentimentsDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
