/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Transactions, transactionsSchema } from './transactions.js';

export interface InsiderTransactions {
  /** Symbol of the company. */
  symbol?: string;
  /** Array of insider transactions. */
  data?: Transactions[];
  additionalProperties?: Record<string, unknown>;
}

export const insiderTransactionsSchema: Schema<InsiderTransactions> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(transactionsSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
