/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InsiderSentimentsData {
  /** Symbol. */
  symbol?: string;
  /** Year. */
  year?: bigint;
  /** Month. */
  month?: bigint;
  /** Net buying/selling from all insiders' transactions. */
  change?: bigint;
  /** Monthly share purchase ratio. */
  mspr?: number;
  additionalProperties?: Record<string, unknown>;
}

export const insiderSentimentsDataSchema: Schema<InsiderSentimentsData> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    year: ['year', optional(bigint())],
    month: ['month', optional(bigint())],
    change: ['change', optional(bigint())],
    mspr: ['mspr', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
