/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InstitutionalOwnershipGroup,
  institutionalOwnershipGroupSchema,
} from './institutionalOwnershipGroup.js';

export interface InstitutionalOwnership {
  /** Symbol. */
  symbol?: string;
  /** Cusip. */
  cusip?: string;
  /** Array of institutional investors. */
  data?: InstitutionalOwnershipGroup[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionalOwnershipSchema: Schema<InstitutionalOwnership> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        cusip: ['cusip', optional(string())],
        data: ['data', optional(array(institutionalOwnershipGroupSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
