/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InstitutionalProfileInfo,
  institutionalProfileInfoSchema,
} from './institutionalProfileInfo.js';

export interface InstitutionalProfile {
  /** CIK. */
  cik?: string;
  /** Array of investors. */
  data?: InstitutionalProfileInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionalProfileSchema: Schema<InstitutionalProfile> = lazy(
  () =>
    typedExpandoObject(
      {
        cik: ['cik', optional(string())],
        data: ['data', optional(array(institutionalProfileInfoSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
