/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InstitutionalOwnershipInfo,
  institutionalOwnershipInfoSchema,
} from './institutionalOwnershipInfo.js';

export interface InstitutionalOwnershipGroup {
  /** Report date. */
  reportDate?: string;
  /** Array of institutional investors. */
  ownership?: InstitutionalOwnershipInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionalOwnershipGroupSchema: Schema<InstitutionalOwnershipGroup> = lazy(
  () =>
    typedExpandoObject(
      {
        reportDate: ['reportDate', optional(string())],
        ownership: [
          'ownership',
          optional(array(institutionalOwnershipInfoSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
