/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InstitutionalPortfolioInfo,
  institutionalPortfolioInfoSchema,
} from './institutionalPortfolioInfo.js';

export interface InstitutionalPortfolioGroup {
  /** Report date. */
  reportDate?: string;
  /** Filing date. */
  filingDate?: string;
  /** Array of positions. */
  portfolio?: InstitutionalPortfolioInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionalPortfolioGroupSchema: Schema<InstitutionalPortfolioGroup> = lazy(
  () =>
    typedExpandoObject(
      {
        reportDate: ['reportDate', optional(string())],
        filingDate: ['filingDate', optional(string())],
        portfolio: [
          'portfolio',
          optional(array(institutionalPortfolioInfoSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
