/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InstitutionalPortfolioInfo {
  /** Symbol. */
  symbol?: string;
  /** CUSIP. */
  cusip?: string;
  /** Position's name. */
  name?: string;
  /** <code>put</code> or <code>call</code> for options. */
  putCall?: string;
  /** Number of shares change. */
  change?: number;
  /** Number of shares with no voting rights. */
  noVoting?: number;
  /** Percentage of portfolio. */
  percentage?: number;
  /** Number of shares. */
  share?: number;
  /** Number of shares with shared voting rights. */
  sharedVoting?: number;
  /** Number of shares with sole voting rights. */
  soleVoting?: number;
  /** Position value. */
  value?: number;
  additionalProperties?: Record<string, unknown>;
}

export const institutionalPortfolioInfoSchema: Schema<InstitutionalPortfolioInfo> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    cusip: ['cusip', optional(string())],
    name: ['name', optional(string())],
    putCall: ['putCall', optional(string())],
    change: ['change', optional(number())],
    noVoting: ['noVoting', optional(number())],
    percentage: ['percentage', optional(number())],
    share: ['share', optional(number())],
    sharedVoting: ['sharedVoting', optional(number())],
    soleVoting: ['soleVoting', optional(number())],
    value: ['value', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
