/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InstitutionalProfileInfo {
  /** Investor's company CIK. */
  cik?: string;
  /** Firm type. */
  firmType?: string;
  /** Manager. */
  manager?: string;
  /** Investing philosophy. */
  philosophy?: string;
  /** Profile info. */
  profile?: string;
  /** Profile image. */
  profileImg?: string;
  additionalProperties?: Record<string, unknown>;
}

export const institutionalProfileInfoSchema: Schema<InstitutionalProfileInfo> = typedExpandoObject(
  {
    cik: ['cik', optional(string())],
    firmType: ['firmType', optional(string())],
    manager: ['manager', optional(string())],
    philosophy: ['philosophy', optional(string())],
    profile: ['profile', optional(string())],
    profileImg: ['profileImg', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
