/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InstitutionalOwnershipInfo {
  /** Investor's company CIK. */
  cik?: string;
  /** Firm's name. */
  name?: string;
  /** <code>put</code> or <code>call</code> for options. */
  putCall?: string;
  /** Number of shares change. */
  change?: number;
  /** Number of shares with no voting rights. */
  noVoting?: number;
  /** Percentage of portfolio. */
  percentage?: number;
  /** News score. */
  share?: number;
  /** Number of shares with shared voting rights. */
  sharedVoting?: number;
  /** Number of shares with sole voting rights. */
  soleVoting?: number;
  /** Position value. */
  value?: number;
  additionalProperties?: Record<string, unknown>;
}

export const institutionalOwnershipInfoSchema: Schema<InstitutionalOwnershipInfo> = typedExpandoObject(
  {
    cik: ['cik', optional(string())],
    name: ['name', optional(string())],
    putCall: ['putCall', optional(string())],
    change: ['change', optional(number())],
    noVoting: ['noVoting', optional(number())],
    percentage: ['percentage', optional(number())],
    share: ['share', optional(number())],
    sharedVoting: ['sharedVoting', optional(number())],
    soleVoting: ['soleVoting', optional(number())],
    value: ['value', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
