/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InstitutionalPortfolioGroup,
  institutionalPortfolioGroupSchema,
} from './institutionalPortfolioGroup.js';

export interface InstitutionalPortfolio {
  /** Investor's name. */
  name?: string;
  /** CIK. */
  cik?: string;
  /** Array of positions. */
  data?: InstitutionalPortfolioGroup[];
  additionalProperties?: Record<string, unknown>;
}

export const institutionalPortfolioSchema: Schema<InstitutionalPortfolio> = lazy(
  () =>
    typedExpandoObject(
      {
        name: ['name', optional(string())],
        cik: ['cik', optional(string())],
        data: ['data', optional(array(institutionalPortfolioGroupSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
