/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InternationalFiling {
  /** Symbol. */
  symbol?: string;
  /** Company name. */
  companyName?: string;
  /** Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
  filedDate?: string;
  /** Category. */
  category?: string;
  /** Document's title. */
  title?: string;
  /** Document's description. */
  description?: string;
  /** Url. */
  url?: string;
  /** Language. */
  language?: string;
  /** Country. */
  country?: string;
  additionalProperties?: Record<string, unknown>;
}

export const internationalFilingSchema: Schema<InternationalFiling> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    companyName: ['companyName', optional(string())],
    filedDate: ['filedDate', optional(string())],
    category: ['category', optional(string())],
    title: ['title', optional(string())],
    description: ['description', optional(string())],
    url: ['url', optional(string())],
    language: ['language', optional(string())],
    country: ['country', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
