/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InvestmentThemePortfolio {
  /** Symbol */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const investmentThemePortfolioSchema: Schema<InvestmentThemePortfolio> = typedExpandoObject(
  { symbol: ['symbol', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
