/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InvestmentThemePortfolio,
  investmentThemePortfolioSchema,
} from './investmentThemePortfolio.js';

export interface InvestmentThemes {
  /** Investment theme */
  theme?: string;
  /** Investment theme portfolio. */
  data?: InvestmentThemePortfolio[];
  additionalProperties?: Record<string, unknown>;
}

export const investmentThemesSchema: Schema<InvestmentThemes> = lazy(() =>
  typedExpandoObject(
    {
      theme: ['theme', optional(string())],
      data: ['data', optional(array(investmentThemePortfolioSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
