/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { IpoEvent, ipoEventSchema } from './ipoEvent.js';

export interface IpoCalendar {
  /** Array of IPO events. */
  ipoCalendar?: IpoEvent[];
  additionalProperties?: Record<string, unknown>;
}

export const ipoCalendarSchema: Schema<IpoCalendar> = lazy(() =>
  typedExpandoObject(
    { ipoCalendar: ['ipoCalendar', optional(array(ipoEventSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
