/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IpoEvent {
  /** Symbol. */
  symbol?: string;
  /** IPO date. */
  date?: string;
  /** Exchange. */
  exchange?: string;
  /** Company's name. */
  name?: string;
  /** IPO status. Can take 1 of the following values: <code>expected</code>,<code>priced</code>,<code>withdrawn</code>,<code>filed</code> */
  status?: string;
  /** Projected price or price range. */
  price?: string;
  /** Number of shares offered during the IPO. */
  numberOfShares?: number;
  /** Total shares value. */
  totalSharesValue?: number;
  additionalProperties?: Record<string, unknown>;
}

export const ipoEventSchema: Schema<IpoEvent> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    date: ['date', optional(string())],
    exchange: ['exchange', optional(string())],
    name: ['name', optional(string())],
    status: ['status', optional(string())],
    price: ['price', optional(string())],
    numberOfShares: ['numberOfShares', optional(number())],
    totalSharesValue: ['totalSharesValue', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
