/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IsinChangeInfo {
  /** Event's date. */
  atDate?: string;
  /** Old ISIN. */
  oldIsin?: string;
  /** New ISIN. */
  newIsin?: string;
  additionalProperties?: Record<string, unknown>;
}

export const isinChangeInfoSchema: Schema<IsinChangeInfo> = typedExpandoObject(
  {
    atDate: ['atDate', optional(string())],
    oldIsin: ['oldIsin', optional(string())],
    newIsin: ['newIsin', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
