/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { IsinChangeInfo, isinChangeInfoSchema } from './isinChangeInfo.js';

export interface IsinChange {
  /** From date. */
  fromDate?: string;
  /** To date. */
  toDate?: string;
  /** Array of ISIN change events. */
  data?: IsinChangeInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const isinChangeSchema: Schema<IsinChange> = lazy(() =>
  typedExpandoObject(
    {
      fromDate: ['fromDate', optional(string())],
      toDate: ['toDate', optional(string())],
      data: ['data', optional(array(isinChangeInfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
