/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface KeyCustomersSuppliers {
  /** Symbol */
  symbol?: string;
  /** Name */
  name?: string;
  /** Country */
  country?: string;
  /** Industry */
  industry?: string;
  /** Whether the company is a customer. */
  customer?: boolean;
  /** Whether the company is a supplier */
  supplier?: boolean;
  /** 1-month price correlation */
  oneMonthCorrelation?: number;
  /** 1-year price correlation */
  oneYearCorrelation?: number;
  /** 6-month price correlation */
  sixMonthCorrelation?: number;
  /** 3-month price correlation */
  threeMonthCorrelation?: number;
  /** 2-week price correlation */
  twoWeekCorrelation?: number;
  /** 2-year price correlation */
  twoYearCorrelation?: number;
  additionalProperties?: Record<string, unknown>;
}

export const keyCustomersSuppliersSchema: Schema<KeyCustomersSuppliers> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    name: ['name', optional(string())],
    country: ['country', optional(string())],
    industry: ['industry', optional(string())],
    customer: ['customer', optional(boolean())],
    supplier: ['supplier', optional(boolean())],
    oneMonthCorrelation: ['oneMonthCorrelation', optional(number())],
    oneYearCorrelation: ['oneYearCorrelation', optional(number())],
    sixMonthCorrelation: ['sixMonthCorrelation', optional(number())],
    threeMonthCorrelation: ['threeMonthCorrelation', optional(number())],
    twoWeekCorrelation: ['twoWeekCorrelation', optional(number())],
    twoYearCorrelation: ['twoYearCorrelation', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
