/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LastBidAsk {
  /** Bid price. */
  b?: number;
  /** Ask price. */
  a?: number;
  /** Bid volume. */
  bv?: number;
  /** Ask volume. */
  av?: number;
  /** Reference UNIX timestamp in ms. */
  t?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const lastBidAskSchema: Schema<LastBidAsk> = typedExpandoObject(
  {
    b: ['b', optional(number())],
    a: ['a', optional(number())],
    bv: ['bv', optional(number())],
    av: ['av', optional(number())],
    t: ['t', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
