/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { LobbyingData, lobbyingDataSchema } from './lobbyingData.js';

export interface LobbyingResult {
  /** Symbol. */
  symbol?: string;
  /** Array of lobbying activities. */
  data?: LobbyingData[];
  additionalProperties?: Record<string, unknown>;
}

export const lobbyingResultSchema: Schema<LobbyingResult> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(lobbyingDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
