/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LobbyingData {
  /** Symbol. */
  symbol?: string;
  /** Company's name. */
  name?: string;
  /** Description. */
  description?: string;
  /** Country. */
  country?: string;
  /** Year. */
  year?: bigint;
  /** Period. */
  period?: string;
  /** Income reported by lobbying firms. */
  income?: number;
  /** Expenses reported by the company. */
  expenses?: number;
  /** Document's URL. */
  documentUrl?: string;
  /** Posted name. */
  postedName?: string;
  /** Date. */
  date?: string;
  /** Client ID. */
  clientId?: string;
  /** Registrant ID. */
  registrantId?: string;
  /** Senate ID. */
  senateId?: string;
  /** House registrant ID. */
  houseregistrantId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const lobbyingDataSchema: Schema<LobbyingData> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    country: ['country', optional(string())],
    year: ['year', optional(bigint())],
    period: ['period', optional(string())],
    income: ['income', optional(number())],
    expenses: ['expenses', optional(number())],
    documentUrl: ['documentUrl', optional(string())],
    postedName: ['postedName', optional(string())],
    date: ['date', optional(string())],
    clientId: ['clientId', optional(string())],
    registrantId: ['registrantId', optional(string())],
    senateId: ['senateId', optional(string())],
    houseregistrantId: ['houseregistrantId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
