/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MarketHolidayData {
  /** Holiday's name. */
  eventName?: string;
  /** Date. */
  atDate?: string;
  /** Trading hours for this day if the market is partially closed only. */
  tradingHour?: string;
  additionalProperties?: Record<string, unknown>;
}

export const marketHolidayDataSchema: Schema<MarketHolidayData> = typedExpandoObject(
  {
    eventName: ['eventName', optional(string())],
    atDate: ['atDate', optional(string())],
    tradingHour: ['tradingHour', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
