/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MarketStatus {
  /** Exchange. */
  exchange?: string;
  /** Timezone. */
  timezone?: string;
  /** Market session. Can be 1 of the following values: <code>pre-market</code>,<code>regular</code>,<code>post-market</code> or <code>null</code> if the market is closed. */
  session?: string;
  /** Holiday event. */
  holiday?: string;
  /** Whether the market is open at the moment. */
  isOpen?: boolean;
  /** Current timestamp. */
  t?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const marketStatusSchema: Schema<MarketStatus> = typedExpandoObject(
  {
    exchange: ['exchange', optional(string())],
    timezone: ['timezone', optional(string())],
    session: ['session', optional(string())],
    holiday: ['holiday', optional(string())],
    isOpen: ['isOpen', optional(boolean())],
    t: ['t', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
