/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MarketHolidayData,
  marketHolidayDataSchema,
} from './marketHolidayData.js';

export interface MarketHoliday {
  /** Timezone. */
  timezone?: string;
  /** Exchange. */
  exchange?: string;
  /** Array of holidays. */
  data?: MarketHolidayData[];
  additionalProperties?: Record<string, unknown>;
}

export const marketHolidaySchema: Schema<MarketHoliday> = lazy(() =>
  typedExpandoObject(
    {
      timezone: ['timezone', optional(string())],
      exchange: ['exchange', optional(string())],
      data: ['data', optional(array(marketHolidayDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
