/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MarketCapData {
  /** Date of the reading */
  atDate?: string;
  /** Value */
  marketCapitalization?: number;
  additionalProperties?: Record<string, unknown>;
}

export const marketCapDataSchema: Schema<MarketCapData> = typedExpandoObject(
  {
    atDate: ['atDate', optional(string())],
    marketCapitalization: ['marketCapitalization', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
