/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MutualFundHoldingsData,
  mutualFundHoldingsDataSchema,
} from './mutualFundHoldingsData.js';

export interface MutualFundHoldings {
  /** Symbol. */
  symbol?: string;
  /** Holdings update date. */
  atDate?: string;
  /** Number of holdings. */
  numberOfHoldings?: bigint;
  /** Array of holdings. */
  holdings?: MutualFundHoldingsData[];
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundHoldingsSchema: Schema<MutualFundHoldings> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      atDate: ['atDate', optional(string())],
      numberOfHoldings: ['numberOfHoldings', optional(bigint())],
      holdings: ['holdings', optional(array(mutualFundHoldingsDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
