/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MutualFundSectorExposureData,
  mutualFundSectorExposureDataSchema,
} from './mutualFundSectorExposureData.js';

export interface MutualFundSectorExposure {
  /** Mutual symbol. */
  symbol?: string;
  /** Array of sector and exposure levels. */
  sectorExposure?: MutualFundSectorExposureData[];
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundSectorExposureSchema: Schema<MutualFundSectorExposure> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        sectorExposure: [
          'sectorExposure',
          optional(array(mutualFundSectorExposureDataSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
