/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MutualFundProfileData,
  mutualFundProfileDataSchema,
} from './mutualFundProfileData.js';

export interface MutualFundProfile {
  /** Symbol. */
  symbol?: string;
  profile?: MutualFundProfileData;
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundProfileSchema: Schema<MutualFundProfile> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      profile: ['profile', optional(mutualFundProfileDataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
