/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MutualFundProfileData {
  /** Name */
  name?: string;
  /** Fund's category. */
  category?: string;
  /** Investment Segment. */
  investmentSegment?: string;
  /** NAV. */
  totalNav?: number;
  /** Expense ratio. */
  expenseRatio?: number;
  /** Index benchmark. */
  benchmark?: string;
  /** Inception date. */
  inceptionDate?: string;
  /** Fund's description. */
  description?: string;
  /** Fund Family. */
  fundFamily?: string;
  /** Fund Company. */
  fundCompany?: string;
  /** Fund's managers. */
  manager?: string;
  /** Status. */
  status?: string;
  /** Beta. */
  beta?: number;
  /** Deferred load. */
  deferredLoad?: number;
  /** 12B-1 fee. */
  fee12B1?: number;
  /** Front Load. */
  frontLoad?: number;
  /** IRA minimum investment. */
  iraMinInvestment?: number;
  /** ISIN. */
  isin?: string;
  /** CUSIP. */
  cusip?: string;
  /** Max redemption fee. */
  maxRedemptionFee?: number;
  /** Minimum investment for standard accounts. */
  standardMinInvestment?: number;
  /** Turnover. */
  turnover?: number;
  /** Fund's series ID. This field can be used to group multiple share classes into 1 unique fund. */
  seriesId?: string;
  /** Fund's series name. */
  seriesName?: string;
  /** Class ID. */
  classId?: string;
  /** Class name. */
  className?: string;
  /** SFDR classification for EU funds. Under the new classifications, a fund's strategy will labeled under either Article 6, 8 or 9. Article 6 covers funds which do not integrate any kind of sustainability into the investment process. Article 8, also known as ‘environmental and socially promoting’, applies “… where a financial product promotes, among other characteristics, environmental or social characteristics, or a combination of those characteristics, provided that the companies in which the investments are made follow good governance practices.”. Article 9, also known as ‘products targeting sustainable investments’, covers products targeting bespoke sustainable investments and applies “… where a financial product has sustainable investment as its objective and an index has been designated as a reference benchmark.” */
  sfdrClassification?: string;
  /** Fund's currency */
  currency?: string;
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundProfileDataSchema: Schema<MutualFundProfileData> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    category: ['category', optional(string())],
    investmentSegment: ['investmentSegment', optional(string())],
    totalNav: ['totalNav', optional(number())],
    expenseRatio: ['expenseRatio', optional(number())],
    benchmark: ['benchmark', optional(string())],
    inceptionDate: ['inceptionDate', optional(string())],
    description: ['description', optional(string())],
    fundFamily: ['fundFamily', optional(string())],
    fundCompany: ['fundCompany', optional(string())],
    manager: ['manager', optional(string())],
    status: ['status', optional(string())],
    beta: ['beta', optional(number())],
    deferredLoad: ['deferredLoad', optional(number())],
    fee12B1: ['fee12b1', optional(number())],
    frontLoad: ['frontLoad', optional(number())],
    iraMinInvestment: ['iraMinInvestment', optional(number())],
    isin: ['isin', optional(string())],
    cusip: ['cusip', optional(string())],
    maxRedemptionFee: ['maxRedemptionFee', optional(number())],
    standardMinInvestment: ['standardMinInvestment', optional(number())],
    turnover: ['turnover', optional(number())],
    seriesId: ['seriesId', optional(string())],
    seriesName: ['seriesName', optional(string())],
    classId: ['classId', optional(string())],
    className: ['className', optional(string())],
    sfdrClassification: ['sfdrClassification', optional(string())],
    currency: ['currency', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
