/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MutualFundCountryExposureData,
  mutualFundCountryExposureDataSchema,
} from './mutualFundCountryExposureData.js';

export interface MutualFundCountryExposure {
  /** Symbol. */
  symbol?: string;
  /** Array of countries and and exposure levels. */
  countryExposure?: MutualFundCountryExposureData[];
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundCountryExposureSchema: Schema<MutualFundCountryExposure> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        countryExposure: [
          'countryExposure',
          optional(array(mutualFundCountryExposureDataSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
