/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MutualFundCountryExposureData {
  /** Country */
  country?: string;
  /** Percent of exposure. */
  exposure?: number;
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundCountryExposureDataSchema: Schema<MutualFundCountryExposureData> = typedExpandoObject(
  {
    country: ['country', optional(string())],
    exposure: ['exposure', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
