/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MutualFundEetPai {
  /** ISIN. */
  isin?: string;
  data?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const mutualFundEetPaiSchema: Schema<MutualFundEetPai> = typedExpandoObject(
  { isin: ['isin', optional(string())], data: ['data', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
