/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NetIncomeEstimatesInfo {
  /** Average net income estimates including Finnhub's proprietary estimates. */
  netIncomeAvg?: number;
  /** Highest estimate. */
  netIncomeHigh?: number;
  /** Lowest estimate. */
  netIncomeLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const netIncomeEstimatesInfoSchema: Schema<NetIncomeEstimatesInfo> = typedExpandoObject(
  {
    netIncomeAvg: ['netIncomeAvg', optional(number())],
    netIncomeHigh: ['netIncomeHigh', optional(number())],
    netIncomeLow: ['netIncomeLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
