/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { NewsroomArticle, newsroomArticleSchema } from './newsroomArticle.js';

export interface Newsroom {
  /** Company symbol. */
  symbol?: string;
  /** Array of articles. */
  data?: NewsroomArticle[];
  additionalProperties?: Record<string, unknown>;
}

export const newsroomSchema: Schema<Newsroom> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(newsroomArticleSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
