/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NewsroomArticle {
  /** Published time in <code>YYYY-MM-DD HH:MM:SS</code> format (EST timezone). */
  atDate?: string;
  /** Title. */
  title?: string;
  /** URL to download the full text data. */
  fullText?: string;
  /** Original URL. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const newsroomArticleSchema: Schema<NewsroomArticle> = typedExpandoObject(
  {
    atDate: ['atDate', optional(string())],
    title: ['title', optional(string())],
    fullText: ['fullText', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
