/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CompanyNewsStatistics,
  companyNewsStatisticsSchema,
} from './companyNewsStatistics.js';
import { Sentiment, sentimentSchema } from './sentiment.js';

export interface NewsSentiment {
  buzz?: CompanyNewsStatistics;
  /** News score. */
  companyNewsScore?: number;
  /** Sector average bullish percent. */
  sectorAverageBullishPercent?: number;
  /** Sectore average score. */
  sectorAverageNewsScore?: number;
  sentiment?: Sentiment;
  /** Requested symbol. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const newsSentimentSchema: Schema<NewsSentiment> = lazy(() =>
  typedExpandoObject(
    {
      buzz: ['buzz', optional(companyNewsStatisticsSchema)],
      companyNewsScore: ['companyNewsScore', optional(number())],
      sectorAverageBullishPercent: [
        'sectorAverageBullishPercent',
        optional(number()),
      ],
      sectorAverageNewsScore: ['sectorAverageNewsScore', optional(number())],
      sentiment: ['sentiment', optional(sentimentSchema)],
      symbol: ['symbol', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
