/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OcfEstimatesInfo {
  /** Average OCF estimates including Finnhub's proprietary estimates. */
  ocfAvg?: number;
  /** Highest estimate. */
  ocfHigh?: number;
  /** Lowest estimate. */
  ocfLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const ocfEstimatesInfoSchema: Schema<OcfEstimatesInfo> = typedExpandoObject(
  {
    ocfAvg: ['ocfAvg', optional(number())],
    ocfHigh: ['ocfHigh', optional(number())],
    ocfLow: ['ocfLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
