/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OwnershipInfo, ownershipInfoSchema } from './ownershipInfo.js';

export interface Ownership {
  /** Symbol of the company. */
  symbol?: string;
  /** Array of investors with detailed information about their holdings. */
  ownership?: OwnershipInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const ownershipSchema: Schema<Ownership> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      ownership: ['ownership', optional(array(ownershipInfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
