/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PatternRecognition {
  /** Array of patterns. */
  points?: unknown[];
  additionalProperties?: Record<string, unknown>;
}

export const patternRecognitionSchema: Schema<PatternRecognition> = typedExpandoObject(
  { points: ['points', optional(array(unknown()))] },
  'additionalProperties',
  optional(unknown())
);
