/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PresentationData {
  /** Quarter */
  quarter?: bigint;
  /** Year */
  year?: bigint;
  /** Presentation url */
  url?: string;
  /** Title */
  title?: string;
  /** At Time. */
  atTime?: string;
  additionalProperties?: Record<string, unknown>;
}

export const presentationDataSchema: Schema<PresentationData> = typedExpandoObject(
  {
    quarter: ['quarter', optional(bigint())],
    year: ['year', optional(bigint())],
    url: ['url', optional(string())],
    title: ['title', optional(string())],
    atTime: ['atTime', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
