/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Development, developmentSchema } from './development.js';

export interface PressRelease {
  /** Company symbol. */
  symbol?: string;
  /** Array of major developments. */
  majorDevelopment?: Development[];
  additionalProperties?: Record<string, unknown>;
}

export const pressReleaseSchema: Schema<PressRelease> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      majorDevelopment: [
        'majorDevelopment',
        optional(array(developmentSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
