/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PretaxIncomeEstimatesInfo,
  pretaxIncomeEstimatesInfoSchema,
} from './pretaxIncomeEstimatesInfo.js';

export interface PretaxIncomeEstimates {
  /** List of estimates */
  data?: PretaxIncomeEstimatesInfo[];
  /** Frequency: annual or quarterly. */
  freq?: string;
  /** Company symbol. */
  symbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const pretaxIncomeEstimatesSchema: Schema<PretaxIncomeEstimates> = lazy(
  () =>
    typedExpandoObject(
      {
        data: ['data', optional(array(pretaxIncomeEstimatesInfoSchema))],
        freq: ['freq', optional(string())],
        symbol: ['symbol', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
