/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PretaxIncomeEstimatesInfo {
  /** Average pretax income estimates including Finnhub's proprietary estimates. */
  pretaxIncomeAvg?: number;
  /** Highest estimate. */
  pretaxIncomeHigh?: number;
  /** Lowest estimate. */
  pretaxIncomeLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const pretaxIncomeEstimatesInfoSchema: Schema<PretaxIncomeEstimatesInfo> = typedExpandoObject(
  {
    pretaxIncomeAvg: ['pretaxIncomeAvg', optional(number())],
    pretaxIncomeHigh: ['pretaxIncomeHigh', optional(number())],
    pretaxIncomeLow: ['pretaxIncomeLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
