/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PriceMetrics {
  /** Symbol of the company. */
  symbol?: string;
  /** Data date. */
  atDate?: string;
  data?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const priceMetricsSchema: Schema<PriceMetrics> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    atDate: ['atDate', optional(string())],
    data: ['data', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
