/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PriceTarget {
  /** Company symbol. */
  symbol?: string;
  /** Highes analysts' target. */
  targetHigh?: number;
  /** Lowest analysts' target. */
  targetLow?: number;
  /** Mean of all analysts' targets. */
  targetMean?: number;
  /** Median of all analysts' targets. */
  targetMedian?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Updated time of the data */
  lastUpdated?: string;
  additionalProperties?: Record<string, unknown>;
}

export const priceTargetSchema: Schema<PriceTarget> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    targetHigh: ['targetHigh', optional(number())],
    targetLow: ['targetLow', optional(number())],
    targetMean: ['targetMean', optional(number())],
    targetMedian: ['targetMedian', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    lastUpdated: ['lastUpdated', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
