/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Quote {
  /** Open price of the day */
  o?: number;
  /** High price of the day */
  h?: number;
  /** Low price of the day */
  l?: number;
  /** Current price */
  c?: number;
  /** Previous close price */
  pc?: number;
  /** Change */
  d?: number;
  /** Percent change */
  dp?: number;
  additionalProperties?: Record<string, unknown>;
}

export const quoteSchema: Schema<Quote> = typedExpandoObject(
  {
    o: ['o', optional(number())],
    h: ['h', optional(number())],
    l: ['l', optional(number())],
    c: ['c', optional(number())],
    pc: ['pc', optional(number())],
    d: ['d', optional(number())],
    dp: ['dp', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
