/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RecommendationTrend {
  /** Company symbol. */
  symbol?: string;
  /** Number of recommendations that fall into the Buy category */
  buy?: bigint;
  /** Number of recommendations that fall into the Hold category */
  hold?: bigint;
  /** Updated period */
  period?: string;
  /** Number of recommendations that fall into the Sell category */
  sell?: bigint;
  /** Number of recommendations that fall into the Strong Buy category */
  strongBuy?: bigint;
  /** Number of recommendations that fall into the Strong Sell category */
  strongSell?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const recommendationTrendSchema: Schema<RecommendationTrend> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    buy: ['buy', optional(bigint())],
    hold: ['hold', optional(bigint())],
    period: ['period', optional(string())],
    sell: ['sell', optional(bigint())],
    strongBuy: ['strongBuy', optional(bigint())],
    strongSell: ['strongSell', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
