/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Report {
  /** Access number. */
  accessNumber?: string;
  /** Symbol. */
  symbol?: string;
  /** CIK. */
  cik?: string;
  /** Year. */
  year?: bigint;
  /** Quarter. */
  quarter?: bigint;
  /** Form type. */
  form?: string;
  /** Period start date <code>%Y-%m-%d %H:%M:%S</code>. */
  startDate?: string;
  /** Period end date <code>%Y-%m-%d %H:%M:%S</code>. */
  endDate?: string;
  /** Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
  filedDate?: string;
  /** Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
  acceptedDate?: string;
  report?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const reportSchema: Schema<Report> = typedExpandoObject(
  {
    accessNumber: ['accessNumber', optional(string())],
    symbol: ['symbol', optional(string())],
    cik: ['cik', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
    form: ['form', optional(string())],
    startDate: ['startDate', optional(string())],
    endDate: ['endDate', optional(string())],
    filedDate: ['filedDate', optional(string())],
    acceptedDate: ['acceptedDate', optional(string())],
    report: ['report', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
