/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BreakdownItem, breakdownItemSchema } from './breakdownItem.js';

export interface RevenueBreakdown {
  /** Symbol */
  symbol?: string;
  /** CIK */
  cik?: string;
  /** Array of revenue breakdown over multiple periods. */
  data?: BreakdownItem[];
  additionalProperties?: Record<string, unknown>;
}

export const revenueBreakdownSchema: Schema<RevenueBreakdown> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      cik: ['cik', optional(string())],
      data: ['data', optional(array(breakdownItemSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
