/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RevenueBreakdown2 {
  /** Symbol */
  symbol?: string;
  /** currency */
  currency?: string;
  /** Revenue breakdown data. */
  data?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const revenueBreakdown2Schema: Schema<RevenueBreakdown2> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    currency: ['currency', optional(string())],
    data: ['data', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
