/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RevenueEstimatesInfo {
  /** Average revenue estimates including Finnhub's proprietary estimates. */
  revenueAvg?: number;
  /** Highest estimate. */
  revenueHigh?: number;
  /** Lowest estimate. */
  revenueLow?: number;
  /** Number of Analysts. */
  numberAnalysts?: bigint;
  /** Period. */
  period?: string;
  /** Fiscal year. */
  year?: bigint;
  /** Fiscal quarter. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const revenueEstimatesInfoSchema: Schema<RevenueEstimatesInfo> = typedExpandoObject(
  {
    revenueAvg: ['revenueAvg', optional(number())],
    revenueHigh: ['revenueHigh', optional(number())],
    revenueLow: ['revenueLow', optional(number())],
    numberAnalysts: ['numberAnalysts', optional(bigint())],
    period: ['period', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
