/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SearchBody {
  /** Search query */
  query: string;
  /** List of isin to search, comma separated (Max: 50). */
  isins?: string;
  /** List of cusip to search, comma separated (Max: 50). */
  cusips?: string;
  /** List of SEC Center Index Key to search, comma separated (Max: 50). */
  ciks?: string;
  /** List of SEDAR issuer number to search, comma separated (Max: 50). */
  sedarIds?: string;
  /** List of Companies House number to search, comma separated (Max: 50). */
  chIds?: string;
  /** List of symbols to search, comma separated (Max: 50). */
  symbols?: string;
  /** List of sedols to search, comma separated (Max: 50). */
  sedols?: string;
  /** List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  sources?: string;
  /** List of forms to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  forms?: string;
  /** List of gics to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  gics?: string;
  /** List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  naics?: string;
  /** List of exhibits to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  exhibits?: string;
  /** List of exchanges to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  exchanges?: string;
  /** List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values. */
  countries?: string;
  /** List of SEC's exchanges act to search, comma separated. Look at <code>/filter</code> endpoint to see all available values. */
  acts?: string;
  /** List of market capitalization to search, comma separated. Look at <code>/filter</code> endpoint to see all available values. */
  caps?: string;
  /** Search from date in format: YYYY-MM-DD, default from the last 2 years */
  fromDate?: string;
  /** Search to date in format: YYYY-MM-DD, default to today */
  toDate?: string;
  /** Use for pagination, default to page 1 */
  page?: string;
  /** Sort result by, default: sortMostRecent. Look at <code>/filter</code> endpoint to see all available values. */
  sort?: string;
  /** Enable highlight in returned filings. If enabled, only return 10 results each time */
  highlighted?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const searchBodySchema: Schema<SearchBody> = typedExpandoObject(
  {
    query: ['query', string()],
    isins: ['isins', optional(string())],
    cusips: ['cusips', optional(string())],
    ciks: ['ciks', optional(string())],
    sedarIds: ['sedarIds', optional(string())],
    chIds: ['chIds', optional(string())],
    symbols: ['symbols', optional(string())],
    sedols: ['sedols', optional(string())],
    sources: ['sources', optional(string())],
    forms: ['forms', optional(string())],
    gics: ['gics', optional(string())],
    naics: ['naics', optional(string())],
    exhibits: ['exhibits', optional(string())],
    exchanges: ['exchanges', optional(string())],
    countries: ['countries', optional(string())],
    acts: ['acts', optional(string())],
    caps: ['caps', optional(string())],
    fromDate: ['fromDate', optional(string())],
    toDate: ['toDate', optional(string())],
    page: ['page', optional(string())],
    sort: ['sort', optional(string())],
    highlighted: ['highlighted', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
