/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FilingResponse, filingResponseSchema } from './filingResponse.js';

export interface SearchResponse {
  /** Total filing matched your search criteria. */
  count?: number;
  /** Time took to execute your search query on our server, value in ms. */
  took?: number;
  /** Current search page */
  page?: number;
  /** Filing match your search criteria. */
  filings?: FilingResponse[];
  additionalProperties?: Record<string, unknown>;
}

export const searchResponseSchema: Schema<SearchResponse> = lazy(() =>
  typedExpandoObject(
    {
      count: ['count', optional(number())],
      took: ['took', optional(number())],
      page: ['page', optional(number())],
      filings: ['filings', optional(array(filingResponseSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
