/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FilingSentiment, filingSentimentSchema } from './filingSentiment.js';

export interface SecSentimentAnalysis {
  /** Access number. */
  accessNumber?: string;
  /** Symbol. */
  symbol?: string;
  /** CIK. */
  cik?: string;
  sentiment?: FilingSentiment;
  additionalProperties?: Record<string, unknown>;
}

export const secSentimentAnalysisSchema: Schema<SecSentimentAnalysis> = lazy(
  () =>
    typedExpandoObject(
      {
        accessNumber: ['accessNumber', optional(string())],
        symbol: ['symbol', optional(string())],
        cik: ['cik', optional(string())],
        sentiment: ['sentiment', optional(filingSentimentSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
