/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SectorMetricData {
  /** Sector */
  sector?: string;
  /** Metrics data in key-value format. <code>a</code> and <code>m</code> fields are for average and median respectively. */
  metrics?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const sectorMetricDataSchema: Schema<SectorMetricData> = typedExpandoObject(
  {
    sector: ['sector', optional(string())],
    metrics: ['metrics', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
