/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SectorMetricData,
  sectorMetricDataSchema,
} from './sectorMetricData.js';

export interface SectorMetric {
  /** Region. */
  region?: string;
  /** Metrics for each sector. */
  data?: SectorMetricData[];
  additionalProperties?: Record<string, unknown>;
}

export const sectorMetricSchema: Schema<SectorMetric> = lazy(() =>
  typedExpandoObject(
    {
      region: ['region', optional(string())],
      data: ['data', optional(array(sectorMetricDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
