/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SentimentContent {
  /** Number of mentions */
  mention?: bigint;
  /** Number of positive mentions */
  positiveMention?: bigint;
  /** Number of negative mentions */
  negativeMention?: bigint;
  /** Positive score. Range 0-1 */
  positiveScore?: number;
  /** Negative score. Range 0-1 */
  negativeScore?: number;
  /** Final score. Range: -1 to 1 with 1 is very positive and -1 is very negative */
  score?: number;
  /** Period. */
  atTime?: string;
  additionalProperties?: Record<string, unknown>;
}

export const sentimentContentSchema: Schema<SentimentContent> = typedExpandoObject(
  {
    mention: ['mention', optional(bigint())],
    positiveMention: ['positiveMention', optional(bigint())],
    negativeMention: ['negativeMention', optional(bigint())],
    positiveScore: ['positiveScore', optional(number())],
    negativeScore: ['negativeScore', optional(number())],
    score: ['score', optional(number())],
    atTime: ['atTime', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
