/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Sentiment {
  bearishPercent?: number;
  bullishPercent?: number;
  additionalProperties?: Record<string, unknown>;
}

export const sentimentSchema: Schema<Sentiment> = typedExpandoObject(
  {
    bearishPercent: ['bearishPercent', optional(number())],
    bullishPercent: ['bullishPercent', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
