/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SimilarityIndexInfo {
  /** CIK. */
  cik?: string;
  /** Cosine similarity of Item 1 (Business). This number is only available for Annual reports. */
  item1?: number;
  /** Cosine similarity of Item 1A (Risk Factors). This number is available for both Annual and Quarterly reports. */
  item1A?: number;
  /** Cosine similarity of Item 2 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Quarterly reports. */
  item2?: number;
  /** Cosine similarity of Item 7 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Annual reports. */
  item7?: number;
  /** Cosine similarity of Item 7A (Quantitative and Qualitative Disclosures About Market Risk). This number is only available for Annual reports. */
  item7A?: number;
  /** Access number. */
  accessNumber?: string;
  /** Form type. */
  form?: string;
  /** Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
  filedDate?: string;
  /** Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
  acceptedDate?: string;
  /** Report's URL. */
  reportUrl?: string;
  /** Filing's URL. */
  filingUrl?: string;
  additionalProperties?: Record<string, unknown>;
}

export const similarityIndexInfoSchema: Schema<SimilarityIndexInfo> = typedExpandoObject(
  {
    cik: ['cik', optional(string())],
    item1: ['item1', optional(number())],
    item1A: ['item1a', optional(number())],
    item2: ['item2', optional(number())],
    item7: ['item7', optional(number())],
    item7A: ['item7a', optional(number())],
    accessNumber: ['accessNumber', optional(string())],
    form: ['form', optional(string())],
    filedDate: ['filedDate', optional(string())],
    acceptedDate: ['acceptedDate', optional(string())],
    reportUrl: ['reportUrl', optional(string())],
    filingUrl: ['filingUrl', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
