/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SimilarityIndexInfo,
  similarityIndexInfoSchema,
} from './similarityIndexInfo.js';

export interface SimilarityIndex {
  /** Symbol. */
  symbol?: string;
  /** CIK. */
  cik?: string;
  /** Array of filings with its cosine similarity compared to the same report of the previous year. */
  similarity?: SimilarityIndexInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const similarityIndexSchema: Schema<SimilarityIndex> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      cik: ['cik', optional(string())],
      similarity: ['similarity', optional(array(similarityIndexInfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
