/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SentimentContent,
  sentimentContentSchema,
} from './sentimentContent.js';

export interface SocialSentiment {
  /** Company symbol. */
  symbol?: string;
  /** Sentiment data. */
  data?: SentimentContent[];
  additionalProperties?: Record<string, unknown>;
}

export const socialSentimentSchema: Schema<SocialSentiment> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(sentimentContentSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
