/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Split {
  /** Symbol. */
  symbol?: string;
  /** Split date. */
  date?: string;
  /** From factor. */
  fromFactor?: number;
  /** To factor. */
  toFactor?: number;
  additionalProperties?: Record<string, unknown>;
}

export const splitSchema: Schema<Split> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    date: ['date', optional(string())],
    fromFactor: ['fromFactor', optional(number())],
    toFactor: ['toFactor', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
