/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PresentationData,
  presentationDataSchema,
} from './presentationData.js';

export interface StockPresentation {
  /** Company symbol. */
  symbol?: string;
  /** Presentation data. */
  res?: PresentationData[];
  additionalProperties?: Record<string, unknown>;
}

export const stockPresentationSchema: Schema<StockPresentation> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      res: ['res', optional(array(presentationDataSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
