/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StockSymbol {
  /** Symbol description */
  description?: string;
  /** Display symbol name. */
  displaySymbol?: string;
  /** Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint. */
  symbol?: string;
  /** Security type. */
  type?: string;
  /** Primary exchange's MIC. */
  mic?: string;
  /** FIGI identifier. */
  figi?: string;
  /** Global Share Class FIGI. */
  shareClassFigi?: string;
  /** Price's currency. This might be different from the reporting currency of fundamental data. */
  currency?: string;
  /** Alternative ticker for exchanges with multiple tickers for 1 stock such as BSE. */
  symbol2?: string;
  /** ISIN. This field is only available for EU stocks and selected Asian markets. Entitlement from Finnhub is required to access this field. */
  isin?: string;
  additionalProperties?: Record<string, unknown>;
}

export const stockSymbolSchema: Schema<StockSymbol> = typedExpandoObject(
  {
    description: ['description', optional(string())],
    displaySymbol: ['displaySymbol', optional(string())],
    symbol: ['symbol', optional(string())],
    type: ['type', optional(string())],
    mic: ['mic', optional(string())],
    figi: ['figi', optional(string())],
    shareClassFigi: ['shareClassFIGI', optional(string())],
    currency: ['currency', optional(string())],
    symbol2: ['symbol2', optional(string())],
    isin: ['isin', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
