/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StockTranscripts {
  /** Transcript's ID used to get the <a href="#transcripts">full transcript</a>. */
  id?: string;
  /** Title. */
  title?: string;
  /** Time of the event. */
  time?: string;
  /** Year of earnings result in the case of earnings call transcript. */
  year?: bigint;
  /** Quarter of earnings result in the case of earnings call transcript. */
  quarter?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const stockTranscriptsSchema: Schema<StockTranscripts> = typedExpandoObject(
  {
    id: ['id', optional(string())],
    title: ['title', optional(string())],
    time: ['time', optional(string())],
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
