/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SupportResistance {
  /** Array of support and resistance levels. */
  levels?: number[];
  additionalProperties?: Record<string, unknown>;
}

export const supportResistanceSchema: Schema<SupportResistance> = typedExpandoObject(
  { levels: ['levels', optional(array(number()))] },
  'additionalProperties',
  optional(unknown())
);
