/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  KeyCustomersSuppliers,
  keyCustomersSuppliersSchema,
} from './keyCustomersSuppliers.js';

export interface SupplyChainRelationships {
  /** symbol */
  symbol?: string;
  /** Key customers and suppliers. */
  data?: KeyCustomersSuppliers[];
  additionalProperties?: Record<string, unknown>;
}

export const supplyChainRelationshipsSchema: Schema<SupplyChainRelationships> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        data: ['data', optional(array(keyCustomersSuppliersSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
