/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SymbolLookupInfo,
  symbolLookupInfoSchema,
} from './symbolLookupInfo.js';

export interface SymbolLookup {
  /** Array of search results. */
  result?: SymbolLookupInfo[];
  /** Number of results. */
  count?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const symbolLookupSchema: Schema<SymbolLookup> = lazy(() =>
  typedExpandoObject(
    {
      result: ['result', optional(array(symbolLookupInfoSchema))],
      count: ['count', optional(bigint())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
