/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SymbolChangeInfo {
  /** Event's date. */
  atDate?: string;
  /** Old symbol. */
  oldSymbol?: string;
  /** New symbol. */
  newSymbol?: string;
  additionalProperties?: Record<string, unknown>;
}

export const symbolChangeInfoSchema: Schema<SymbolChangeInfo> = typedExpandoObject(
  {
    atDate: ['atDate', optional(string())],
    oldSymbol: ['oldSymbol', optional(string())],
    newSymbol: ['newSymbol', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
