/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SymbolChangeInfo,
  symbolChangeInfoSchema,
} from './symbolChangeInfo.js';

export interface SymbolChange {
  /** From date. */
  fromDate?: string;
  /** To date. */
  toDate?: string;
  /** Array of symbol change events. */
  data?: SymbolChangeInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const symbolChangeSchema: Schema<SymbolChange> = lazy(() =>
  typedExpandoObject(
    {
      fromDate: ['fromDate', optional(string())],
      toDate: ['toDate', optional(string())],
      data: ['data', optional(array(symbolChangeInfoSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
