/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Indicator, indicatorSchema } from './indicator.js';

export interface TechnicalAnalysis {
  count?: Indicator;
  /** Aggregate Signal */
  signal?: string;
  additionalProperties?: Record<string, unknown>;
}

export const technicalAnalysisSchema: Schema<TechnicalAnalysis> = lazy(() =>
  typedExpandoObject(
    {
      count: ['count', optional(indicatorSchema)],
      signal: ['signal', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
