/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TickData {
  /** Symbol. */
  s?: string;
  /** Number of ticks skipped. */
  skip?: bigint;
  /** Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
  count?: bigint;
  /** Total number of ticks for that date. */
  total?: bigint;
  /** List of volume data. */
  v?: number[];
  /** List of price data. */
  p?: number[];
  /** List of timestamp in UNIX ms. */
  t?: bigint[];
  /** List of venues/exchanges. A list of exchange codes can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing",>here</a> */
  x?: string[];
  /** List of trade conditions. A comprehensive list of trade conditions code can be found <a target="_blank" href="https://docs.google.com/spreadsheets/d/1PUxiSWPHSODbaTaoL2Vef6DgU-yFtlRGZf19oBb9Hp0/edit?usp=sharing">here</a> */
  c?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const tickDataSchema: Schema<TickData> = typedExpandoObject(
  {
    s: ['s', optional(string())],
    skip: ['skip', optional(bigint())],
    count: ['count', optional(bigint())],
    total: ['total', optional(bigint())],
    v: ['v', optional(array(number()))],
    p: ['p', optional(array(number()))],
    t: ['t', optional(array(bigint()))],
    x: ['x', optional(array(string()))],
    c: ['c', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
