/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Transactions {
  /** Symbol. */
  symbol?: string;
  /** Insider's name. */
  name?: string;
  /** Number of shares held after the transaction. */
  share?: bigint;
  /** Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction. */
  change?: bigint;
  /** Filing date. */
  filingDate?: string;
  /** Transaction date. */
  transactionDate?: string;
  /** Average transaction price. */
  transactionPrice?: number;
  /** Transaction code. A list of codes and their meanings can be found <a href="https://www.sec.gov/about/forms/form4data.pdf" target="_blank" rel="noopener">here</a>. */
  transactionCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const transactionsSchema: Schema<Transactions> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    name: ['name', optional(string())],
    share: ['share', optional(bigint())],
    change: ['change', optional(bigint())],
    filingDate: ['filingDate', optional(string())],
    transactionDate: ['transactionDate', optional(string())],
    transactionPrice: ['transactionPrice', optional(number())],
    transactionCode: ['transactionCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
