/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TranscriptContent {
  /** Speaker's name */
  name?: string;
  /** Speaker's speech */
  speech?: string[];
  /** Earnings calls section (management discussion or Q&A) */
  session?: string;
  additionalProperties?: Record<string, unknown>;
}

export const transcriptContentSchema: Schema<TranscriptContent> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    speech: ['speech', optional(array(string()))],
    session: ['session', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
