/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TranscriptParticipant {
  /** Participant's name */
  name?: string;
  /** Participant's description */
  description?: string;
  /** Whether the speak is a company's executive or an analyst */
  role?: string;
  additionalProperties?: Record<string, unknown>;
}

export const transcriptParticipantSchema: Schema<TranscriptParticipant> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    role: ['role', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
