/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Trend {
  /** ADX reading */
  adx?: number;
  /** Whether market is trending or going sideway */
  trending?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const trendSchema: Schema<Trend> = typedExpandoObject(
  {
    adx: ['adx', optional(number())],
    trending: ['trending', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
