/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UpgradeDowngrade {
  /** Company symbol. */
  symbol?: string;
  /** Upgrade/downgrade time in UNIX timestamp. */
  gradeTime?: bigint;
  /** From grade. */
  fromGrade?: string;
  /** To grade. */
  toGrade?: string;
  /** Company/analyst who did the upgrade/downgrade. */
  company?: string;
  /** Action can take any of the following values: <code>up(upgrade), down(downgrade), main(maintains), init(initiate), reit(reiterate)</code>. */
  action?: string;
  additionalProperties?: Record<string, unknown>;
}

export const upgradeDowngradeSchema: Schema<UpgradeDowngrade> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    gradeTime: ['gradeTime', optional(bigint())],
    fromGrade: ['fromGrade', optional(string())],
    toGrade: ['toGrade', optional(string())],
    company: ['company', optional(string())],
    action: ['action', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
