/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UsaSpending {
  /** Symbol. */
  symbol?: string;
  /** Company's name. */
  recipientName?: string;
  /** Company's name. */
  recipientParentName?: string;
  /** Description. */
  awardDescription?: string;
  /** Recipient's country. */
  country?: string;
  /** Period. */
  actionDate?: string;
  /** Income reported by lobbying firms. */
  totalValue?: number;
  /** Performance start date. */
  performanceStartDate?: string;
  /** Performance end date. */
  performanceEndDate?: string;
  /** Award agency. */
  awardingAgencyName?: string;
  /** Award sub-agency. */
  awardingSubAgencyName?: string;
  /** Award office name. */
  awardingOfficeName?: string;
  /** Performance country. */
  performanceCountry?: string;
  /** Performance city. */
  performanceCity?: string;
  /** Performance county. */
  performanceCounty?: string;
  /** Performance state. */
  performanceState?: string;
  /** Performance zip code. */
  performanceZipCode?: string;
  /** Performance congressional district. */
  performanceCongressionalDistrict?: string;
  /** NAICS code. */
  naicsCode?: string;
  /** Permalink. */
  permalink?: string;
  additionalProperties?: Record<string, unknown>;
}

export const usaSpendingSchema: Schema<UsaSpending> = typedExpandoObject(
  {
    symbol: ['symbol', optional(string())],
    recipientName: ['recipientName', optional(string())],
    recipientParentName: ['recipientParentName', optional(string())],
    awardDescription: ['awardDescription', optional(string())],
    country: ['country', optional(string())],
    actionDate: ['actionDate', optional(string())],
    totalValue: ['totalValue', optional(number())],
    performanceStartDate: ['performanceStartDate', optional(string())],
    performanceEndDate: ['performanceEndDate', optional(string())],
    awardingAgencyName: ['awardingAgencyName', optional(string())],
    awardingSubAgencyName: ['awardingSubAgencyName', optional(string())],
    awardingOfficeName: ['awardingOfficeName', optional(string())],
    performanceCountry: ['performanceCountry', optional(string())],
    performanceCity: ['performanceCity', optional(string())],
    performanceCounty: ['performanceCounty', optional(string())],
    performanceState: ['performanceState', optional(string())],
    performanceZipCode: ['performanceZipCode', optional(string())],
    performanceCongressionalDistrict: [
      'performanceCongressionalDistrict',
      optional(string()),
    ],
    naicsCode: ['naicsCode', optional(string())],
    permalink: ['permalink', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
