/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { UsaSpending, usaSpendingSchema } from './usaSpending.js';

export interface UsaSpendingResult {
  /** Symbol. */
  symbol?: string;
  /** Array of government's spending data points. */
  data?: UsaSpending[];
  additionalProperties?: Record<string, unknown>;
}

export const usaSpendingResultSchema: Schema<UsaSpendingResult> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(usaSpendingSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
