/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { UsptoPatent, usptoPatentSchema } from './usptoPatent.js';

export interface UsptoPatentResult {
  /** Symbol. */
  symbol?: string;
  /** Array of patents. */
  data?: UsptoPatent[];
  additionalProperties?: Record<string, unknown>;
}

export const usptoPatentResultSchema: Schema<UsptoPatentResult> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', optional(string())],
      data: ['data', optional(array(usptoPatentSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
