/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UsptoPatent {
  /** Application Number. */
  applicationNumber?: string;
  /** Array of companies' name on the patent. */
  companyFilingName?: string[];
  /** Filing date. */
  filingDate?: string;
  /** Description. */
  description?: string;
  /** Filing status. */
  filingStatus?: string;
  /** Patent number. */
  patentNumber?: string;
  /** Publication date. */
  publicationDate?: string;
  /** Patent's type. */
  patentType?: string;
  /** URL of the original article. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const usptoPatentSchema: Schema<UsptoPatent> = typedExpandoObject(
  {
    applicationNumber: ['applicationNumber', optional(string())],
    companyFilingName: ['companyFilingName', optional(array(string()))],
    filingDate: ['filingDate', optional(string())],
    description: ['description', optional(string())],
    filingStatus: ['filingStatus', optional(string())],
    patentNumber: ['patentNumber', optional(string())],
    publicationDate: ['publicationDate', optional(string())],
    patentType: ['patentType', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
