/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface VisaApplication {
  /** Year. */
  year?: bigint;
  /** Quarter. */
  quarter?: bigint;
  /** Symbol. */
  symbol?: string;
  /** Case number. */
  caseNumber?: string;
  /** Case status. */
  caseStatus?: string;
  /** Received date. */
  receivedDate?: string;
  /** Visa class. */
  visaClass?: string;
  /** Job Title. */
  jobTitle?: string;
  /** SOC Code. A list of SOC code can be found <a href="https://www.bls.gov/oes/current/oes_stru.htm" target="_blank">here</a>. */
  socCode?: string;
  /** Full-time position flag. */
  fullTimePosition?: string;
  /** Job's start date. */
  beginDate?: string;
  /** Job's end date. */
  endDate?: string;
  /** Company's name. */
  employerName?: string;
  /** Worksite address. */
  worksiteAddress?: string;
  /** Worksite city. */
  worksiteCity?: string;
  /** Worksite county. */
  worksiteCounty?: string;
  /** Worksite state. */
  worksiteState?: string;
  /** Worksite postal code. */
  worksitePostalCode?: string;
  /** Wage range from. */
  wageRangeFrom?: number;
  /** Wage range to. */
  wageRangeTo?: number;
  /** Wage unit of pay. */
  wageUnitOfPay?: string;
  /** Wage level. */
  wageLevel?: string;
  /** H1B dependent flag. */
  h1BDependent?: string;
  additionalProperties?: Record<string, unknown>;
}

export const visaApplicationSchema: Schema<VisaApplication> = typedExpandoObject(
  {
    year: ['year', optional(bigint())],
    quarter: ['quarter', optional(bigint())],
    symbol: ['symbol', optional(string())],
    caseNumber: ['caseNumber', optional(string())],
    caseStatus: ['caseStatus', optional(string())],
    receivedDate: ['receivedDate', optional(string())],
    visaClass: ['visaClass', optional(string())],
    jobTitle: ['jobTitle', optional(string())],
    socCode: ['socCode', optional(string())],
    fullTimePosition: ['fullTimePosition', optional(string())],
    beginDate: ['beginDate', optional(string())],
    endDate: ['endDate', optional(string())],
    employerName: ['employerName', optional(string())],
    worksiteAddress: ['worksiteAddress', optional(string())],
    worksiteCity: ['worksiteCity', optional(string())],
    worksiteCounty: ['worksiteCounty', optional(string())],
    worksiteState: ['worksiteState', optional(string())],
    worksitePostalCode: ['worksitePostalCode', optional(string())],
    wageRangeFrom: ['wageRangeFrom', optional(number())],
    wageRangeTo: ['wageRangeTo', optional(number())],
    wageUnitOfPay: ['wageUnitOfPay', optional(string())],
    wageLevel: ['wageLevel', optional(string())],
    h1BDependent: ['h1bDependent', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
