/**
 * Finnhub APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { VisaApplication, visaApplicationSchema } from './visaApplication.js';

export interface VisaApplicationResult {
  /** Symbol. */
  symbol?: string;
  /** Array of H1b and Permanent visa applications. */
  data?: VisaApplication[];
  additionalProperties?: Record<string, unknown>;
}

export const visaApplicationResultSchema: Schema<VisaApplicationResult> = lazy(
  () =>
    typedExpandoObject(
      {
        symbol: ['symbol', optional(string())],
        data: ['data', optional(array(visaApplicationSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
